conditionals-simple_programs_with_decision_points-medium-q5
canvas-gamification/canvas-gamification-junit-tests pull request #111
Opened 2022-04-01 15:58 UTC by Hedgemon4

2022-04-01 18:41 UTC, SamamthaH approved these changes

2022-04-01 19:39 UTC, SanaBob submitted a review, later dismissed

2022-04-01 23:17 UTC, Opeyem1a requested changes
Looks good, just minor fixes

2022-04-01 23:17 UTC, Opeyem1a commented on src/conditionals/simple_programs_with_decision_points/medium/q5/MainTest.java
> +                (bonus)? new NewLine() : new StringLiteral("")
Pure nitpick, but you need the parentheses around the `bonus`?

2022-04-01 23:17 UTC, Opeyem1a commented on src/conditionals/simple_programs_with_decision_points/medium/q5/MainTest.java
> +        assertEquals(Double.parseDouble(getItemByName("salary")), outputSalary, 0.01, "The calculated salary values was incorrect.");
"The calculated salary values was incorrect." => "The calculated salary value is incorrect."

2022-04-07 20:52 UTC, SamamthaH approved these changes

2022-04-11 23:29 UTC, Opeyem1a approved these changes

2022-04-11 23:29 UTC, merged