pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q8
canvas-gamification/canvas-gamification-junit-tests pull request #236
Opened 2022-06-30 01:00 UTC by yuqi88

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
---

## Not yet, but soon

- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2022-07-03 04:21 UTC, yuqi88 commented
@Hedgemon4 The question asks for 3 digits and then prints out the reverse version. 
The current solution code takes `.nextInt()`, but in the case of `input = 120`, 
the reverse will be printed as `012`. Because it's typed integer. I don't think this is right.

Should we change the solution code to `.nextLine()` and reverse the input as a string instead?

2022-07-03 20:19 UTC, Hedgemon4 commented
> @Hedgemon4 The question asks for 3 digits and then prints out the reverse version. The current solution code takes `.nextInt()`, but in the case of `input = 120`, the reverse will be printed as `012`. Because it's typed integer. I don't think this is right.
> 
> Should we change the solution code to `.nextLine()` and reverse the input as a string instead?

I think that because this is in the numeric user input section, it should still take in an int, but then outputs a String instead of an int. We can just change it so it is `String reversePlate = "" + num3 + num2 + num1` and then print that.

2022-07-03 20:20 UTC, Hedgemon4 requested changes

2022-07-03 20:20 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/ReversePlate.java
> +Traffic speed cameras are used to catch drivers who speed. One of the issues with this system is that it reads the plate
Also, I don't imagine this will work with negative numbers, so we should probably specify that the numbers will be positive.

2022-07-04 17:41 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/MainTest.java
> +    //Parson
`// Parsons`

2022-07-04 17:42 UTC, Hedgemon4 requested changes
Change parsons comment

2022-07-06 16:02 UTC, Hedgemon4 requested changes

2022-07-06 16:02 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/ReversePlate.java
> + and that all 3 digits are entered ( plate 008 should have the 2 zero enter too. 8 is not a valid plate.)
Also, the way this is now, would it not print 008? I think this is a valid plate

2022-07-06 16:02 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/MainTest.java
> +    // Parson
`// Parsons`

2022-07-09 21:11 UTC, yuqi88 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/ReversePlate.java
> + and that all 3 digits are entered ( plate 008 should have the 2 zero enter too. 8 is not a valid plate.)
if the user typed 8, the program will treat it as 008, so the output will be 800 which makes sense from a programming perspective. But from a user's perspective, it's weird. It's like they typed in an unfinished input, accidentally press enter and still got a valid output.

2022-07-09 21:25 UTC, yuqi88 commented
There's a issue of using `String reversePlate = "" + num3 + num2 + num1`.
It works for input = 800. We will get a correct output = 008. 
But it does not work for input = 008. We will get a incorrect output = 80000.

Using `String reversePlate = num3 + num2 + num1 + ""` will produce a similar result except input = 800 becomes incorrect & input 008 becomes correct this time.

To solve this issue, I'll add an assumption to the question that no zeros are allowed on the plates.

2022-07-20 20:08 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/ReversePlate.java
> +Assuming all users enter exactly 3 digits from 1 to 9 (Zeros are not allowed).
```suggestion
Assume all users enter exactly 3 digits from 1 to 9 (Zeros are not allowed).
```

2022-07-23 22:07 UTC, Hedgemon4 requested changes

2022-07-23 22:07 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q9/MainTest.java
> +    // Parson
```suggestion
    // Parsons
```

2022-07-23 22:08 UTC, Hedgemon4 approved these changes

2022-07-23 22:08 UTC, merged