conditionals-program_with_decision_points-medium-q9
canvas-gamification/canvas-gamification-junit-tests pull request #260
Opened 2022-07-05 02:33 UTC by ketphan02

## PR Checklist
- [x]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
---

## Not yet, but soon

- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2022-07-05 15:22 UTC, Hedgemon4 requested changes

2022-07-07 00:13 UTC, ketphan02 commented on src/conditionals/programs_with_decision_points/medium/q9/GenerationGap.java
> +public class GenerationGap {
It's been formatted 🤔

2022-07-08 21:56 UTC, Hedgemon4 requested changes

2022-07-08 21:56 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/medium/q9/MainTest.java
> +    TestOption.incorrectStructureErrorMessage = "Your program does not correctly print a correct generation for the given year.";
Change error message to `Your program does not print the correct generation for the given year.`

2022-07-08 21:56 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/medium/q9/GenerationGap.java
> + * Anyone else is "Uncategorized."
Change the final sentence to `Anyone else born after 1900 should be labelled as Uncategorized.`

2022-07-15 18:29 UTC, Hedgemon4 approved these changes

2022-07-15 18:30 UTC, merged