pre_defined_classes-simple_programs_taking_string_user_input-medium-q8
canvas-gamification/canvas-gamification-junit-tests pull request #264
Opened 2022-07-08 06:51 UTC by yuqi88

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-07-10 00:40 UTC, yuqi88 commented
Changed the question to deal with `new RandomChar( 'A', (char) ('Z' + 1), "ranChar1")` and that 'Z'+1 in the ASCII table is [.

2022-07-10 00:45 UTC, yuqi88 commented
Issue with RandomChar( ) clause:
The test will not pass given `System.lineSeparator()` as the input.
This might be something @Hedgemon4 you want to look into. Seems like it's a similar issue as the RandomInteger( ).
#222 

For now, I'll add a clarification to the question so that no-value input is not allowed.

![image](https://user-images.githubusercontent.com/60047943/178126964-dd8474cf-1016-4c7c-b594-200aa2e725c2.png)

2022-07-16 17:40 UTC, Hedgemon4 commented
Waiting for https://github.com/canvas-gamification/canvas-gamification-junit-tests/issues/272

2022-07-16 22:13 UTC, Opeyem1a commented
Should be fixed once framework changes are pushed 👍🏾

2022-07-20 20:46 UTC, Hedgemon4 requested changes

2022-07-20 20:46 UTC, Hedgemon4 commented on src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q8/UserName.java
> +by adding three random letters from A to Z (including both ends) to the original desired username. Assume all usernames
```suggestion
by adding three random letters from A to Z (inclusive) to the original desired username. Assume all usernames
```

2022-07-24 01:21 UTC, Hedgemon4 approved these changes

2022-07-24 01:21 UTC, merged