conditionals-program_with_decision_points-hard-q7
canvas-gamification/canvas-gamification-junit-tests pull request #281
Opened 2022-07-11 23:45 UTC by ketphan02

## PR Checklist
- [x]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-07-15 00:02 UTC, Hedgemon4 requested changes

2022-07-15 00:02 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/MainTest.java
> +        Arguments.of(5000, "Moderate Risk"),
I would try to not always test the exact middle number, something more random is less predictable (maybe 6739 for example).

2022-07-15 00:02 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/MainTest.java
> +    TestOption.incorrectStructureErrorMessage = "Your program does not print the error message for the invalid input.";
Remove the in `... error message for the invalid input.`

2022-07-15 02:32 UTC, ketphan02 commented on src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
> + * approximate risk of infection based on the following information: Less than 1000 people is "Low Risk", Between
@Hedgemon4 I don't think I understand this

2022-07-15 18:45 UTC, Hedgemon4 requested changes

2022-07-15 18:45 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
> + * approximate risk of infection based on the following information: Less than 1000 people is "Low Risk", Between
Oh, I just think that it is random to just be like `display the approximate risk of infection` I think it should be something like `display the approximate risk of contracting the flu` or something

2022-07-15 18:45 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
> + * approximate risk of infection based on the following information: Less than 1000 people is "Low Risk", Between
It just felt a little clunky to me

2022-07-15 18:45 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/MainTest.java
> +    TestOption.incorrectStructureErrorMessage = "Your program does not print the error message for invalid input.";
`an error message`

2022-07-20 18:29 UTC, Hedgemon4 requested changes

2022-07-20 18:29 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
> + * message if the user provides an invalid input.
```suggestion
 * message if the user provides an invalid input (numbers less than or equal to 0).
```

2022-07-22 23:49 UTC, Hedgemon4 approved these changes

2022-07-22 23:49 UTC, merged