Loops programs with repetition hard q7
canvas-gamification/canvas-gamification-junit-tests pull request #315
Opened 2022-07-17 01:57 UTC by SamamthaH

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-07-17 21:37 UTC, Hedgemon4 requested changes

2022-07-17 21:37 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +Write a program called SinOfTheTimes that will calculate an approximation of sin(x) from n = 0 until n = 10, with x = 3.14,
I think we should change this question to specify one of the two numbers, so they can't hardcode it.

2022-07-17 21:37 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +Write a program called SinOfTheTimes that will calculate an approximation of sin(x) from n = 0 until n = 10, with x = 3.14,
And then we can vary the other one on the website

2022-07-20 23:49 UTC, Hedgemon4 requested changes

2022-07-20 23:49 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +Write a program called SinOfTheTimes that will calculate an approximation of sin(x) from n = 0 until n = 10, with x = 3.14,
Yeah, but if we change the values, they could still just use something like wolfram alpha to quickly calculate the series, and then just print that out.

2022-07-22 15:52 UTC, SamamthaH commented
I've changed it over to an input test but in doing so realized there's actually a problem with running this program with java's limited int size. We can't make n greater than 5 because afterwards the factorials get too big for java integers to handle, and we can't approximate higher than 4.4 without the approximation going higher than 1 or lower than -1 for an unknown reason. Because the n is so limited people won't need to use loops, they can just hardcode in 5 lines of the equation so I don't know if this can work as an actual question.

2022-07-22 23:06 UTC, Hedgemon4 requested changes

2022-07-22 23:06 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +Write a program called SinOfTheTimes that will calculate an approximation of sin(x) from n = 0 until n = 5, with x = 3.14,
This text is not up to date with the question being changed to have an input.

2022-07-22 23:06 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +	Approximation of sin(3.14) using n = 5 is …
The sample output is also out of date.

2022-07-22 23:08 UTC, Hedgemon4 commented
> I've changed it over to an input test but in doing so realized there's actually a problem with running this program with java's limited int size. We can't make n greater than 5 because afterwards the factorials get too big for java integers to handle, and we can't approximate higher than 4.4 without the approximation going higher than 1 or lower than -1 for an unknown reason. Because the n is so limited people won't need to use loops, they can just hardcode in 5 lines of the equation so I don't know if this can work as an actual question.

This can be solved by changing the calculation to use double values instead of integer ones.

2022-07-23 21:41 UTC, Hedgemon4 requested changes

2022-07-23 21:41 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
> +	Approximation of sin(3.14) using n = 10 is …
```suggestion
    Approximation of sin(3.14) using n = 10 is x
```

2022-07-23 21:41 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/MainTest.java
> +        assertEquals(approx, getItemByName("approx"), "Your approximation is incorrect.");
```suggestion
        assertEquals(approx, getItemByName("approx"), "Your approximation of sin(x) is incorrect.");
```

2022-07-23 21:41 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/MainTest.java
> +        assertEquals(approx, getItemByName("approx"), "Your approximation is incorrect.");
```suggestion
        assertEquals(approx, getItemByName("approx"), "Your approximation of sin(x) is incorrect.");
```

2022-07-23 21:41 UTC, Hedgemon4 commented on src/loops/programs_with_repetition/hard/q7/MainTest.java
> +    void correctApproximationCalculated(double in, String approx){
```suggestion
    void calculatesApproximationCorrectly(double in, String approx){
```

2022-07-23 21:42 UTC, Hedgemon4 approved these changes

2022-07-23 21:42 UTC, merged