loops-for_loops-hard-q6
canvas-gamification/canvas-gamification-junit-tests pull request #322
Opened 2022-07-18 02:55 UTC by ketphan02

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-07-20 19:10 UTC, Hedgemon4 requested changes

2022-07-20 19:10 UTC, Hedgemon4 commented on src/loops/for_loops/hard/q6/MainTest.java
> +        new IntegerLiteral(factorial),
Name this so you can `getItemByName` for the assert

2022-07-23 00:02 UTC, ketphan02 commented on src/loops/for_loops/hard/q6/MainTest.java
> +    } });
I think I used it wrong lol

2022-07-23 00:38 UTC, Hedgemon4 submitted a review, later dismissed

2022-07-23 00:38 UTC, Hedgemon4 commented on src/loops/for_loops/hard/q6/MainTest.java
> +    TestOption.incorrectStructureErrorMessage = "Your program does not print the output correctly.";
```suggestion
    TestOption.incorrectStructureErrorMessage = "Your program does not calculate and print the factorial of the entered number correctly.";
```

2022-07-23 00:38 UTC, Hedgemon4 commented on src/loops/for_loops/hard/q6/MainTest.java
> +    TestOption.incorrectStructureErrorMessage = "Your program does not print out the error message for invalid input.";
```suggestion
    TestOption.incorrectStructureErrorMessage = "Your program does not print out an error message for invalid input.";
```

2022-07-23 00:38 UTC, Hedgemon4 commented on src/loops/for_loops/hard/q6/MainTest.java
> +  public void printsErrorForInvalidInput(int n) throws InvalidClauseException {
```suggestion
  public void printsErrorMessageForInvalidInput(int n) throws InvalidClauseException {
```

2022-07-23 00:39 UTC, Hedgemon4 approved these changes

2022-07-23 00:39 UTC, merged