Methods defining methods hard q8
canvas-gamification/canvas-gamification-junit-tests pull request #375
Opened 2022-08-13 03:22 UTC by ketphan02

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-09-11 23:07 UTC, Hedgemon4 requested changes

2022-09-11 23:07 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/RentMethod.java
> + * [J] Write a Java Program that asks users for the cost of rent for their housing per month. Then
Change question text to: 
`Write a Java Program that asks users for the cost of rent for their housing per month. Then write a Java method called rentCalc that accepts that value as a double and returns the cost per year for housing as a double. Your program should print the returned value in the main method. `

2022-09-11 23:07 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +    String errorMsg = "Your method \"rentCalcYear()\" does not calculate the yearly rent correctly.";
I would just change it so it has the method name here, like Your method "rentCalc"

2022-09-11 23:07 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +    CustomAssertions._assertEquals(output, rentYearly, 0.01, errorMsg);
We also need to make sure here that we check and see if the student has printed any string output in the method, as they were instructed to print it in the main method

2022-10-28 04:34 UTC, Hedgemon4 requested changes

2022-10-28 04:34 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/RentMethod.java
> +print the returned value in the main method.
For this one add-in that the user will enter a rent greater than or equal to 0

2022-10-28 04:34 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +                Arguments.of(1.1, 13.2));
Add a test for 0

2022-10-28 04:34 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +                Arguments.of(500.0, 6000.0),
Also maybe use more double values with numbers other than zero in the decimal (to make sure they are not losing precision.

2022-11-22 02:12 UTC, Hedgemon4 requested changes

2022-11-22 02:12 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/RentMethod.java
> +print the returned value in the main method. Assume a user input of 0 or greater.
```suggestion
print the returned value in the main method. Assume a user input of 0 or more.
```

2022-11-22 02:12 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +    void correctCalculatesRent(double rentMonthly, double rentYearly) throws Throwable {
```suggestion
    void correctCalculatesRentMethod(double rentMonthly, double rentYearly) throws Throwable {
```

2022-11-22 02:12 UTC, Hedgemon4 commented on src/methods/defining_methods/hard/q8/MainTest.java
> +        assertEquals(Double.parseDouble(getItemByName("rentYearly")), rentYearly, 0.00001, errorMsg);
Should be rentYearly here first

2022-11-22 17:27 UTC, SamamthaH commented on src/methods/defining_methods/hard/q8/MainTest.java
> +    ;
agreed

2022-11-22 18:14 UTC, Hedgemon4 approved these changes

2022-11-22 18:14 UTC, merged