arrays-creating_arrays-hard-q1
canvas-gamification/canvas-gamification-junit-tests pull request #422
Opened 2022-09-17 00:02 UTC by SamamthaH

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-10-20 21:15 UTC, Hedgemon4 requested changes

2022-10-20 21:15 UTC, Hedgemon4 commented on src/arrays/creating_arrays/hard/q1/RandomArray.java
> +Sample output:
Add space between question text and sample output

2022-10-20 21:15 UTC, Hedgemon4 commented on src/arrays/creating_arrays/hard/q1/RandomArray.java
> +5
Tab this over

2022-10-20 21:15 UTC, Hedgemon4 commented on src/arrays/creating_arrays/hard/q1/RandomArray.java
> +Write a Java program that asks the user for the number of elements it will store and uses a method called
Change question text to:
Write a Java program that asks the user to enter a length for an array and then calls a method named createRandomArray() to generate this array. The method should accept an integer for the length and create a new array of that size. Then, it should initialize the array with random numbers from 0 (inclusive) to the passed length (exclusive). Return this array and print the output in the main method.

2023-01-23 06:05 UTC, SamamthaH commented
I think the reason this is framework is because without the try catches we still don't have a good way of checking if the entire array is random ints

2023-05-11 02:57 UTC, Hedgemon4 requested changes

2023-05-11 02:57 UTC, Hedgemon4 commented on src/arrays/creating_arrays/hard/q1/MainTest.java
> +        return Stream.of(1000, 1500, 2000, 3000);
We should probably try some other values that are not so large. With larger values, it is more likely they can pass the random check without actually doing it properly.

2023-06-08 01:24 UTC, Hedgemon4 requested changes

2023-06-08 01:24 UTC, Hedgemon4 commented on src/arrays/creating_arrays/hard/q1/MainTest.java
> +            ArrayList<Integer> response = Arrays.stream(arr).boxed().collect(Collectors.toCollection(ArrayList::new));
We should also verify that the array returned is the correct length

2023-06-09 02:12 UTC, Hedgemon4 approved these changes

2023-06-09 02:12 UTC, merged