arrays-arrays_with_methods-hard-q9
canvas-gamification/canvas-gamification-junit-tests pull request #436
Opened 2022-10-02 05:11 UTC by SamamthaH

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2023-01-27 19:00 UTC, Hedgemon4 requested changes

2023-01-27 19:00 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(one, Integer.parseInt(getItemByName("first")), "Your program does not square the first number.");
All the error messages should be "... square the x number in the array."

2023-02-12 21:24 UTC, SamamthaH commented
Do you want me to change up the test so that the length of the array can be varied in the website?

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/ArrayofDigits.java
> +powerN that takes an integer array, computes the 2nd power of each element, and does not return any output. Back in the main
```suggestion
powerN that takes an integer array and squares each element. The return type of powerN should be void, and it should be generalized to handle any input array length. Back in the main
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertNull(output, "Your powerN method should not have a return variable.");
```suggestion
        assertNull(output, "Your powerN does not have the correct return type.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        CustomAssertions._assertArrayEquals(expected, given, "Your method does not square the values in the given array.");
```suggestion
        CustomAssertions._assertArrayEquals(expected, given, "Your powerN method does not square the values in the input array.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(one, Integer.parseInt(getItemByName("first")), "Your program does not square the first number in the array.");
```suggestion
        assertEquals(one, Integer.parseInt(getItemByName("first")), "Your program does not correctly square and print the array elements.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(two, Integer.parseInt(getItemByName("second")), "Your program does not square the first number in the array.");
```suggestion
        assertEquals(two, Integer.parseInt(getItemByName("second")), "Your program does not correctly square and print the array elements.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(three, Integer.parseInt(getItemByName("third")), "Your program does not square the first number in the array.");
```suggestion
        assertEquals(three, Integer.parseInt(getItemByName("third")), "Your program does not correctly square and print the array elements.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(four, Integer.parseInt(getItemByName("fourth")), "Your program does not square the first number in the array.");
```suggestion
        assertEquals(four, Integer.parseInt(getItemByName("fourth")), "Your program does not correctly square and print the array elements.");
```

2023-02-20 18:54 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q9/MainTest.java
> +        assertEquals(five, Integer.parseInt(getItemByName("fifth")), "Your program does not square the first number in the array.");
```suggestion
        assertEquals(five, Integer.parseInt(getItemByName("fifth")), "Your program does not correctly square and print the array elements.");
```

2023-02-20 18:55 UTC, Hedgemon4 approved these changes

2023-02-20 18:56 UTC, merged