arrays-arrays_with_methods-hard-q10
canvas-gamification/canvas-gamification-junit-tests pull request #437
Opened 2022-10-02 23:19 UTC by SamamthaH

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2023-01-27 19:01 UTC, Hedgemon4 requested changes
Update test cases to use arrayUtil

2023-02-12 21:30 UTC, SamamthaH commented
> Update test cases to use arrayUtil

Is that really necessary? The point of arrayUtil is that it can make very large test cases, but I already have a test case in this that is 1000 size

2023-02-20 19:02 UTC, Hedgemon4 requested changes

2023-02-20 19:02 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q10/ArrayofDigits.java
> +in the main method, display the resulting array that was outputted from the method call.
```suggestion
in the main method, print the array which is returned from the digitInt method.
```

2023-02-20 19:02 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q10/MainTest.java
> +        CustomAssertions._assertArrayEquals(arr, output, "Your digitInt method does not return an array of the specified integers to the specified length.");
```suggestion
        CustomAssertions._assertArrayEquals(arr, output, "Your digitInt method does not return the correct array based on the input parameters.");
```

2023-02-20 19:02 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q10/MainTest.java
> +
We should add a custom error message here I think

2023-02-27 16:00 UTC, Hedgemon4 requested changes

2023-02-27 16:00 UTC, Hedgemon4 commented on src/arrays/arrays_with_methods/hard/q10/MainTest.java
> +        TestOption.incorrectStructureErrorMessage = "Your program does not correctly print the array of integers.";
```suggestion
        TestOption.incorrectStructureErrorMessage = "Your program does not correctly print the generated array of integers.";
```

2023-02-27 16:01 UTC, merged