Q11 is fixed.
canvas-gamification/canvas-gamification-junit-tests pull request #455
Opened 2022-10-23 02:13 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-10-25 18:30 UTC, Hedgemon4 requested changes

2022-10-25 18:30 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q11/Discount.java
> +	Enter your birthday:
Fix the spacing here

2022-10-25 18:30 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q11/Discount.java
> +and if not, print "You do not qualify for any discounts.".
Should be a space between the sample output and the question text.

2022-10-25 18:30 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q11/MainTest.java
> +    static Stream<int[]> InputProviderQualified() {
Switch this to hardcoded inputs instead of returning an array

2022-10-25 18:30 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q11/MainTest.java
> +    void testWithInputQualified(int[] in) throws InvalidClauseException {
You can also combine these into one test instead of two different ones.

2022-10-25 18:30 UTC, Hedgemon4 commented on src/conditionals/programs_with_decision_points/hard/q11/MainTest.java
> +    void testWithInputQualified(int[] in) throws InvalidClauseException {
Also, rename these methods to something more like `identifiesDiscountCorrectly` or something similar.

2022-11-18 01:25 UTC, Hedgemon4 submitted a review, later dismissed

2022-11-26 03:01 UTC, SamamthaH requested changes

2023-01-19 20:05 UTC, SamamthaH requested changes

2023-01-19 20:05 UTC, SamamthaH commented on src/conditionals/programs_with_decision_points/hard/q11/Discount.java
> +	Enter your birthday:
fix this

2023-01-19 20:05 UTC, SamamthaH commented on src/conditionals/programs_with_decision_points/hard/q11/MainTest.java
> +                Arguments.of(1, 1, 2015),
get rid of the 2015s

2023-01-26 22:04 UTC, SamamthaH approved these changes

2023-01-27 00:04 UTC, merged