arrays-referencing_array_and_its_elements-hard-q2
canvas-gamification/canvas-gamification-junit-tests pull request #458
Opened 2022-10-24 22:08 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-10-31 03:38 UTC, Hedgemon4 requested changes

2022-10-31 03:38 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/InThirds.java
> +Write a program called InThirds that defines an array of integers, in this case {3, 4, 6, 21, 48, 42, 89, 2, 0}, and
This question is bad and going to be hard to test thoroughly. Change it to:
`Write a Java program that takes an array of nine numbers from the user and a positive integer x. Then, call a method named remainder(int[] arr, int x) that takes the array and returns the first n numbers in a new array of length n, where n is the remainder after dividing the array length by x. Print the new array in the main method. Assume the user provides valid input. `

2022-10-31 03:38 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/InThirds.java
> +public class InThirds {
Here is the rewritten test code:
```java
import java.util.Scanner;

public class Remainder {
    public static void main(String[] args) {
        System.out.println("Enter nine integers: ");
        Scanner input = new Scanner(System.in);
        int[] arr = new int[9];
        for (int i = 0; i < arr.length; i++)
            arr[i] = input.nextInt();
        System.out.println("Enter a positive integer: ");
        int x = input.nextInt();
        int[] remain = remainder(arr, x);
        for(int i = 0; i < remain.length; i++)
            System.out.println(remain[i]);
    }

    public static int[] remainder(int[] arr, int x){
        int n = arr.length % x;
        int[] remainder = new int[n];
        for (int i = 0; i < n; i++)
            remainder[i] = arr[i];
        return remainder;
    }
}
```

2022-10-31 03:41 UTC, Hedgemon4 requested changes

2022-10-31 03:41 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +        Object output = MethodUtil.invokeIfMethodExists(InThirds.class, "splitter", new Object[]{input}, int[].class);
Also, switch this to MethodTest

2022-11-07 23:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    @ParameterizedTest
Format this code file (ctrl - alt - l)

2022-11-08 00:00 UTC, Hedgemon4 requested changes

2022-11-08 00:00 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +                Arguments.of(a3, 1,  Arrays.copyOfRange(a3, 0, n % 1))
You should also a case where n is the divisor, and maybe one more number (like half of n)

2022-11-09 02:10 UTC, Hedgemon4 requested changes

2022-11-09 02:10 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    void printCorrectOutput(int[] input, int x, int[] ans) throws InvalidClauseException {
```suggestion
    void printsCorrectOutput(int[] input, int x, int[] ans) throws InvalidClauseException {
```

2022-11-09 02:10 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +                Arguments.of(a4, n, Arrays.copyOfRange(a4, 0, n % n)),
I realized this was the same case as one of the previous ones, so maybe change it to n-1 or something instead

2022-11-18 01:39 UTC, Hedgemon4 requested changes

2022-11-18 01:39 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/Remainder.java
> +named remainder(int[] arr, int x) that takes the array and returns the first n numbers in a new array of length n, where
```suggestion
named remainder(int[] arr, int x) that takes the array and returns the first n numbers in a new array of length n, where n
```

2022-11-18 01:39 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +        TestOption.defaultInput = "1 2 3 4 5 6 7 8 9 2";
Generate this instead

2022-11-18 01:39 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +                Arguments.of(a4, n, Arrays.copyOfRange(a4, 0, n % n)),
Remove this case

2022-11-26 02:46 UTC, SamamthaH requested changes

2022-11-26 02:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +                Arguments.of(a5, n - 2, Arrays.copyOfRange(a5, 0, n % (n - 2)))
```suggestion
                Arguments.of(a5, n - 2, Arrays.copyOfRange(a5, 0, 2))
```

2022-11-26 02:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    static Stream<Arguments> InputProvider() {
vary range of generated arrays

2022-12-08 23:29 UTC, SamamthaH requested changes

2022-12-08 23:29 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    static Stream<Arguments> InputProvider() {
```suggestion
    static Stream<Arguments> inputProvider() {
```

2022-12-08 23:29 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    @MethodSource("InputProvider")
```suggestion
    @MethodSource("inputProvider")
```

2022-12-08 23:29 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +    @MethodSource("InputProvider")
```suggestion
    @MethodSource("inputProvider")
```

2022-12-08 23:29 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +        runWithInput(arrayToInput(input) + " " + x, new Clause[]{
There should be an error message set before the runWithInput

2022-12-08 23:29 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q2/MainTest.java
> +                "Your remainder method does not return the correct subarray.");
```suggestion
                "Your remainder method does not correctly return the subarray of the first n numbers.");
```

2023-01-26 22:10 UTC, SamamthaH approved these changes

2023-01-27 00:16 UTC, merged