arrays-referencing_array_and_its_elements-hard-q3
canvas-gamification/canvas-gamification-junit-tests pull request #460
Opened 2022-10-29 20:18 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-10-31 03:40 UTC, Hedgemon4 requested changes

2022-10-31 03:40 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/EvenorOdd.java
> +Write a Java program that defines the array of integers with positive numbers ( [3, 4, 6, 21, 48, 42, 89, 2, 5, 91] ).
This question also needs to be switched to use scanner input so that they can't hardcode based on the array we provide them.

2022-11-08 06:16 UTC, Hedgemon4 requested changes

2022-11-08 06:16 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/EvenorOdd.java
> +Write a Java program that input an array of 10 integers with positive numbers.
For this, I think we should change the question text to be this:
`Write a java program that accepts an array of 10 numbers from the user and then creates a new array of only even numbers from the original array. To do this, create a method named even that accepts an integer array, counts the number of even integers in the array, and then transfers them to a new array of that length. Then, return the new array to the main method, and print out its elements. `

2022-11-08 06:16 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/EvenorOdd.java
> +Write a Java program that input an array of 10 integers with positive numbers.
As such, you will have to update the test

2022-11-08 06:16 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/EvenorOdd.java
> +public class EvenorOdd {
Change this to even

2022-11-18 01:55 UTC, Hedgemon4 submitted a review, later dismissed

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/Even.java
> +integers in the array, and then transfers them to a new array of that length in the same order, note that you method
```suggestion
integers in the array, and then transfer them to a new array of that length in the same order. Note that your method
```

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +        int[] a1 = generateRandomArray(1, 1000000000, n);
We can add a case here where we have only evens and only odd numbers using array util

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                Arguments.of(new int[]{5, 3, 1, 6, 4, 2}),
Same thing here, you should be able to add an array of only evens using method util, and an array of only odds

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                "Your even method does not return the correct even array");
```suggestion
                "Your even method does not correctly create a new array consisting of only even values from the input array.");
```

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                Arguments.of(new int[]{3, 4, 6, 21, 48, 42, 89, 2, 5, 91}),
I would hardcode these as a second argument instead of calling getEven on them

2022-11-18 01:55 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                Arguments.of(generateRandomArray(1, 1000000000, 100000))
Just generate this array and call get even on it

2022-11-26 03:13 UTC, SamamthaH requested changes

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/Even.java
> +Write a java program that accepts an array of 10 numbers from the user and then creates a new array of only even numbers
```suggestion
Write a Java program that accepts an array of 10 integers from the user and then creates a new array of only even numbers
```

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +    public static int[] getEven(int[] arr) {
Change to something like,
int[] evens = new int[n];
int evenCount = 0;
if even
     events[evenCount++] = passedArray[x]
return copy of array using arrayCopy or something

to get a different solution code than the question

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +        return Stream.of(
Vary range of generated arrays

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +
get rid of extra spaces

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                "Your even method does not correctly create a new array consisting of only even values from the input array.");
```suggestion
                "Your even method does not correctly create a new array of the even values from the input array.");
```

2022-11-26 03:13 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +        TestOption.incorrectStructureErrorMessage = "Your main method does not print the correct even array";
```suggestion
        TestOption.incorrectStructureErrorMessage = "Your main method does not print the correct array of even numbers.";
```

2022-12-08 23:33 UTC, SamamthaH requested changes

2022-12-08 23:33 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +    static Stream<Arguments> InputProvider() {
```suggestion
    static Stream<Arguments> inputProvider() {
```

2022-12-08 23:33 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +    @MethodSource("InputProvider")
```suggestion
    @MethodSource("inputProvider")
```

2022-12-08 23:33 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q3/MainTest.java
> +                "Your even method does not correctly create a new array of the even values from the input array.");
```suggestion
                "Your even method does not correctly create a new array containing the even values from the input array.");
```

2023-01-27 00:12 UTC, SamamthaH approved these changes

2023-01-27 00:30 UTC, merged