arrays-referencing_array_and_its_elements-hard-q4
canvas-gamification/canvas-gamification-junit-tests pull request #461
Opened 2022-10-29 23:26 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-10-31 03:42 UTC, Hedgemon4 requested changes

2022-10-31 03:42 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/PotentialGoodStudents.java
> +Write a Java program that defines an array of doubles given the following array [ 73, 15, 71, 67, 5, 96, 91, 12, 5, 82 ],
Same thing here. We need to provide some sort of input to the user so they can't just hardcode this question

2022-11-08 17:08 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                new StringLiteral("Enter " + n + " double numbers:"),
We should also add the optional place holder for a space at the end here, ie:
```java
  new StringLiteral("Enter " + n + " double numbers:"), 
  new Optional(new StringLiteral(" "))
```

2022-11-08 17:09 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                new StringLiteral("Enter " + n + " double numbers:"),
This allows students to print out that end space without getting penalized

2022-11-08 17:10 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(0.0, 100, n)),
You should still have different test cases here, like maybe one that starts at 88 so all of them get printed

2022-11-08 17:11 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        return Stream.of(
Again, if we want to test cases where the length is different than what we specify in the question, we need to tell the student to generalize their method to work with any length.

2022-11-08 17:11 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(new double[]{pivot + 1, pivot + 1, pivot}),
You should also test a case where none get printed

2022-11-08 17:12 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(new double[]{pivot + 1, pivot + 1, pivot}),
And because it is a double, for this case you can do like + 0.00001 instead of + 1

2022-11-09 02:23 UTC, Hedgemon4 requested changes

2022-11-09 02:23 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/PotentialGoodStudents.java
> +Write a Java program that takes an array of 10 doubles between 0 and 100, indicating course grades for ten students.
Change question text to:
`Write a Java program that takes an array of 10 doubles between 0 and 100, indicating course grades for ten students. Then, traverse through the array and print out the index of students on the same line separated by spaces (Eg: "3 4 6 " ) who got above 88% in the course, indicating they are potential candidates for teaching assistants next year. To do this, create a method called PGS that takes the double array of grades and prints out the indices of the candidate students. Your method should be general enough to work with any length of array.`

2022-11-09 02:23 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        TestOption.defaultInput = "76.9 50.8 68.4 95.7 88.6 81.2 89.5 74.9 12.76 64.0";
Let's just autogenerate this because that should make varying the question on the website easier.

2022-11-09 02:23 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(88.0, 100, 10000)),
Instead of using 88 here, use the pivot value you have instead

2022-11-09 02:23 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(0.0, 88.0, 10000)),
Same here

2022-11-18 02:07 UTC, Hedgemon4 requested changes

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(pivot, 100, 10000)),
For this one, it only prints if the number is greater than the pivot, so I think we should have it be pivot + 0.0001 or something

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                }
Add an optional space here so that the student does not lose marks if they don't trim the string

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        m.setIncorrectMethodStructureErrorMessage("Your PGS method does not print the correct indices");
```suggestion
        m.setIncorrectMethodStructureErrorMessage("Your PGS method does not correctly print the indices of potential teaching assistant candidates.");
```

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        Object output = m.callMethod();
If you don't use this object just call the method and get rid of it

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        Object output = m.callMethod();
```suggestion
        m.callMethod();
```

2022-11-18 02:07 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        TestOption.incorrectStructureErrorMessage = "Your main method does not correctly print the indices of potential students.";
```suggestion
        TestOption.incorrectStructureErrorMessage = "Your main method does not correctly print the indices of the potential teaching assistants.";
```

2022-11-27 01:46 UTC, SamamthaH requested changes

2022-11-27 01:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(pivot, 100, n)),
```suggestion
                Arguments.of(generateRandomArray(pivot+1, 100, n)),
```

2022-11-27 01:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        TestOption.incorrectStructureErrorMessage = "Your main method does not correctly print the indices of the potential teaching assistants.";
```suggestion
        TestOption.incorrectStructureErrorMessage = "Your main method does not correctly print the indices of potential teaching assistants.";
```

2022-11-27 01:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +                Arguments.of(generateRandomArray(0.0, 100, 10000)),
vary the lengths of the generated arrays

2022-11-27 01:46 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q4/MainTest.java
> +        m.setIncorrectMethodStructureErrorMessage("Your PGS method does not correctly print the indices of potential teaching assistant candidates.");
```suggestion
        m.setIncorrectMethodStructureErrorMessage("Your PGS method does not correctly print the indices of potential teaching assistants.");
```

2023-01-19 20:58 UTC, SamamthaH approved these changes

2023-01-19 21:59 UTC, merged