arrays-referencing_array_and_its_elements-hard-q6
canvas-gamification/canvas-gamification-junit-tests pull request #469
Opened 2022-11-08 08:31 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-11-08 17:33 UTC, Hedgemon4 requested changes

2022-11-08 17:33 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +                new StringLiteral("Enter an array of size " + n + " to split in half:"),
Add optional

2022-11-08 17:33 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/RightDownTheMiddle.java
> +Write a program takes array of 10 integers and splits the array by grabbing the first half of the array elements and
For this, I am just going to get ride of the array in the splitHalf method solution code because we can't test if they use it and it is redundant.

2022-11-09 02:39 UTC, Hedgemon4 requested changes
See my comments in your other files

2022-11-18 23:25 UTC, Hedgemon4 requested changes

2022-11-18 23:25 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +    void correctMainMethod(int[] input) throws InvalidClauseException {
```suggestion
    void printsCorrectOutput(int[] input) throws InvalidClauseException {
```

2022-11-18 23:25 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/RightDownTheMiddle.java
> +Write a program that takes an array of ten integers and prints a string containing the first half of the array elements.
Change question text to: 
`Write a program that takes an array of ten integers and prints a string containing the first half of the array elements. To do this, create a method called splitHlaf that takes an integer array and returns the string representation of the first half of the array. For this program, assume the first half of the array is equal to array.length/2. Note that the returned string should have spaces between each number and a space at the end. Finally, print the returned string in the main method. Your method should be general enough to work with any size of an array and any size of an integer.`

2022-11-18 23:25 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +                Arguments.of(generateRandomArray(-1000000000, 1000000000, 10)),
```suggestion
                Arguments.of(generateRandomArray(-1000000000, 1000000000, n)),
```

2022-11-18 23:25 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +        m.setIncorrectMethodStructureErrorMessage("Your splitHalf method does not print the first half of the array correctly");
The method is not printing anything, so you don't need this message.

2022-11-18 23:25 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +        assertEquals(output, split(input));
You should use our custom `_assertEquals` here, and the correct answer should come before the student output

2022-11-27 01:53 UTC, SamamthaH requested changes

2022-11-27 01:53 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q6/RightDownTheMiddle.java
> +        for (int i = 0; i < size; i++) {
```suggestion
        for (int i = 0; i < size/2; i++) {
```

2022-11-27 01:53 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q6/RightDownTheMiddle.java
> +            if (i < (size / 2))
```suggestion
```

2022-11-27 01:53 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +        TestOption.defaultInput = "3 4 6 21 48 42 89 2 0 91";
you'll need to generate an array if you have a variable to vary the amount of inputs.

2022-12-11 06:26 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +        CustomAssertions._assertEquals(split(input), output, "Your splitHalf method does not correctly split the array in half.");
Potential for issue to be with return type, so address that in the error message in some way like, "does not correctly return a String containing the first half of the array"

2022-12-11 06:26 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q6/MainTest.java
> +        TestOption.incorrectStructureErrorMessage = "Your program does not correctly split the array in half.";
Change to something like "does not correctly print the first half of the split array."

2022-12-11 06:27 UTC, SamamthaH requested changes
Change the error messages and it should be good

2023-01-27 00:15 UTC, SamamthaH approved these changes

2023-01-27 21:55 UTC, merged