Wrote basic test for Parson question pre defined classes-mathematical…
canvas-gamification/canvas-gamification-junit-tests pull request #47
Opened 2022-02-24 21:07 UTC by Hedgemon4

… program-medium-q2

2022-02-25 23:41 UTC, SanaBob submitted a review, later dismissed
looks good

2022-02-26 00:54 UTC, Opeyem1a requested changes

2022-02-26 00:54 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/medium/q2/HeronTest.java
> +                new StringLiteral("The area of the triangle is: 8.317902379807064 units squared.")
With questions like this we should still check the math with a test - the test should work even if the question was not Parsons

2022-03-06 07:34 UTC, Opeyem1a requested changes

2022-03-06 07:34 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/medium/q2/HeronTest.java
> +        assertEquals(area + "", getItemByName("area"), "Calculated area is inccorect, try again.");
I think you should parse this to a double instead and compare that instead of comparing strings

2022-03-06 07:34 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/medium/q2/HeronTest.java
> +        assertEquals(area + "", getItemByName("area"), "Calculated area is inccorect, try again.");
`...inccorect...` -> spelling error

2022-04-07 20:11 UTC, SamamthaH approved these changes

2022-04-08 06:37 UTC, aadiraju approved these changes
Looks good!

2022-04-11 22:44 UTC, Opeyem1a approved these changes

2022-04-11 22:44 UTC, merged