arrays-referencing_array_and_its_elements-hard-q7
canvas-gamification/canvas-gamification-junit-tests pull request #470
Opened 2022-11-08 09:28 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2022-11-08 17:47 UTC, Hedgemon4 requested changes
See comments in other pull requests

2022-11-08 17:47 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/MainTest.java
> +}
Add EOF line

2022-11-08 17:47 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +Write a java program that takes an array of 10 integers as an input and reverse it. Write a method called Rev that takes
Write a java program that takes an array of ten integers as input and reverses it. For example, the array {1, 2, 3, 4} would become {4, 3, 2, 1}. To do this, create a method called rev that takes an array and reverses it by placing the elements in a new array in reverse order. Then, return this array and print it in the main method.

2022-11-18 23:37 UTC, Hedgemon4 requested changes

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +would become {4, 3, 2, 1}. To do this, create a method called rev that takes an array and reverses it by placing the
```suggestion
would become {4, 3, 2, 1}. To do this, create a method called rev that takes an array of any length and reverses it by placing the
```

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +
Remove this empty line

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +
Remove this empty line

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/MainTest.java
> +        assertEquals(output, reverse(input));
You should use the custom assert `_assertEquals` here, and make sure that the correct answer goes first

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +    public static String Rev(int[] arr) {
I think we should change this method here to return the array instead of the string

2022-11-18 23:37 UTC, Hedgemon4 commented on src/arrays/referencing_array_and_its_elements/hard/q7/TakeItBackNow.java
> +    public static String Rev(int[] arr) {
You will have to redo the question accordingly

2022-11-27 02:01 UTC, SamamthaH commented on src/arrays/referencing_array_and_its_elements/hard/q7/MainTest.java
> +        MethodTest m = new MethodTest(TakeItBackNow.class, "rev", arguments);
Change so solution is calculated before the m.callMethod() in case the students decides to return the passed integer array

2022-11-27 02:01 UTC, SamamthaH approved these changes

2023-01-19 22:11 UTC, SamamthaH approved these changes

2023-01-20 23:29 UTC, SamamthaH commented
Question text needs updating

2023-02-03 22:15 UTC, merged