arrays-programs_involving_multidimensional_data-easy-q9
canvas-gamification/canvas-gamification-junit-tests pull request #500
Opened 2023-01-26 22:01 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”
---
## Website
- [ ] Is the question text on the Gamification document up to date? 
    > Make sure to include the sample output if there is one for the question

2023-01-28 20:12 UTC, SamamthaH requested changes

2023-01-28 20:12 UTC, SamamthaH commented on src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
> +Write a Java program that generates a 2D array of random integers of size 5 by 5, with the range of values from 100-1000
Change to:
"Write a Java program that generates a 5 by 5 2D array of random integers ranging from 100-1000 (inclusive on both ends), and print the 2D array each row on a new line. Divide all the values by 5, then sum all the values in each row and store those sums into a 1D array which is printed to the console."

2023-01-28 20:12 UTC, SamamthaH commented on src/arrays/programs_involving_multidimensional_data/easy/q9/MainTest.java
> +                arr[i][j] = Integer.parseInt(getItemByName(i + " " + j));
Consider moving 
```Java
arr[i][j] /= div;
ans[i] += arr[i][j];
```
into this loop and creating the int[] ans up with arr

2023-01-28 20:12 UTC, SamamthaH commented on src/arrays/programs_involving_multidimensional_data/easy/q9/MainTest.java
> +        CustomAssertions._assertArrayEquals(ans, out, "Your program does not correctly print the array including sum of each rows after division.");
```suggestion
        CustomAssertions._assertArrayEquals(ans, out, "Your program does not correctly print the sum of each modified row.");
```

2023-02-02 22:14 UTC, Hedgemon4 reviewed
See discord messages

2023-02-12 19:28 UTC, Hedgemon4 requested changes

2023-02-12 19:28 UTC, Hedgemon4 commented on src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
> +
We should definitely have a sample output for this question

2023-02-12 19:40 UTC, Hedgemon4 commented on src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
> +and print the 2D array for each row on a new line. Divide all the values by 5, then sum all the values in each row and
```suggestion
and print the 2D array with each row a seperate line. Divide all the values by 5, then sum all the values in each row and
```

2023-02-12 19:40 UTC, Hedgemon4 commented on src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
> +store those sums into a 1D array printed to the console.
```suggestion
store those sums into a 1D array. Print the sums array to the console.
```

2023-02-12 19:40 UTC, Hedgemon4 submitted a review, later dismissed

2023-02-12 19:45 UTC, Hedgemon4 commented on src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
> +store those sums into a 1D array. Print the sums array to the console.
```suggestion
store those sums into a 1D array. Print the array of sums to the console.
```

2023-02-12 19:45 UTC, merged