pre-defined classes-mathematical program-hard-q6
canvas-gamification/canvas-gamification-junit-tests pull request #60
Opened 2022-02-26 08:13 UTC by SamamthaH

Wrote out clause for Shout Out. Waiting on double literal to write a test that checks the math.

2022-03-10 08:04 UTC, SanaBob commented on src/pre_defined_classes/mathematical_program/hard/q6/ShoutOutTest.java
> +                new DoubleLiteral(0.8749999999999999, 0.8749999999999999, "math")
Add a bit more flexibility in double integral, +/- 0.001 maybe from middle

2022-03-10 08:18 UTC, SanaBob commented on src/pre_defined_classes/mathematical_program/hard/q6/ShoutOutTest.java
> +        assertEquals("0.8749999999999999", getItemByName("math"), "Your math is incorrect");
parseDouble here to not compare strings

2022-03-11 01:23 UTC, SanaBob approved these changes

2022-03-12 00:14 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/MainTest.java
> +    //Parsons
`// Parsons (with Distractors)`

2022-03-12 00:14 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/MainTest.java
> +                new DoubleLiteral("math")
Same comment about the math variable name, I would name it something more specific, because without context I don't know what it is

2022-03-14 05:56 UTC, SamamthaH commented on src/pre_defined_classes/mathematical_program/hard/q6/MainTest.java
> +        assertEquals(0.8749999999999999, Double.parseDouble(getItemByName("math")), 0.1, "Your math is incorrect");
why?

2022-04-07 17:12 UTC, Hedgemon4 requested changes

2022-04-07 17:12 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/ShoutOut.java
> +To calculate the deciBel values of a particular sound, we use the formula: dB = 10 log(Ip/I0), Where Ip is the intensity
Fix the B in decibel

2022-04-07 17:12 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/ShoutOut.java
> +        System.out.println("The ratio of the decibel values between a person speak and a person shouting is " + dBRatio);
Should say speaking instead of speak

2022-04-07 17:12 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/ShoutOut.java
> +        System.out.println("The ratio of the decibel values between a person speak and a person shouting is " + dBRatio);
And I would also say who is speaking/ who is shouting

2022-04-07 17:12 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q6/MainTest.java
> +
Actual test looks good though

2022-04-11 22:49 UTC, Opeyem1a approved these changes

2022-04-11 22:49 UTC, merged