pre-defined classes-mathematical program-hard-q7
canvas-gamification/canvas-gamification-junit-tests pull request #61
Opened 2022-02-26 08:21 UTC by SamamthaH

Wrote out clause for Water. Waiting on double literal to write a test that checks the math.

2022-03-04 03:56 UTC, Hedgemon4 requested changes

2022-03-04 03:56 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q7/WaterTest.java
> +        assertEquals("7.0", getItemByName("math"), "Your math is incorrect");
Same as before, this test would never be failed because DoubleLiteral only accepts 7

2022-03-12 17:15 UTC, Hedgemon4 requested changes

2022-03-12 17:15 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q7/MainTest.java
> +                new DoubleLiteral("math"),
I would rename this to something more specific

2022-03-12 17:15 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q7/MainTest.java
> +        assertEquals(7.0, Double.parseDouble(getItemByName("math")), 0.1, "Your math is incorrect");
I think you should also change the error message to something more specific

2022-03-17 02:44 UTC, Hedgemon4 submitted a review, later dismissed
Looks good to me

2022-03-18 19:32 UTC, aadiraju submitted a review, later dismissed
This looks good to me! Great job! I'll let @Opeyem1a take a look and merge it in!

2022-03-18 20:24 UTC, Opeyem1a requested changes

2022-03-18 20:24 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/hard/q7/MainTest.java
> +        assertEquals(7.0, Double.parseDouble(getItemByName("speed")), 0.1, "Your speed calculation is incorrect. Try referring back to the question for what the correct calculation should look like")
Massive nitpick but end this with a period and it's good to merge

2022-03-20 01:32 UTC, Opeyem1a approved these changes

2022-03-25 20:18 UTC, Opeyem1a approved these changes

2022-04-01 22:50 UTC, merged