pre-defined classes-mathematical program-hard-q9
canvas-gamification/canvas-gamification-junit-tests pull request #63
Opened 2022-02-26 19:35 UTC by SamamthaH

Wrote out clause for GrowthRate. Waiting on double literal to provide a better error message.

2022-03-10 08:06 UTC, SanaBob commented on src/pre_defined_classes/mathematical_program/hard/q9/GrowthRateTest.java
> +                new DoubleLiteral(56.25, 56.25, "math")
add a bit of space between double integral +/- 0.1 maybe

2022-03-10 08:19 UTC, SanaBob commented on src/pre_defined_classes/mathematical_program/hard/q9/GrowthRateTest.java
> +        assertEquals("56.25", getItemByName("math"));
parseDouble and error statement

2022-03-12 17:26 UTC, Hedgemon4 requested changes

2022-03-12 17:26 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
> +                new DoubleLiteral("math")
Variable name

2022-03-12 17:26 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
> +    //Parsons
`\\ Parsons (with distractractors)`

2022-03-12 17:26 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
> +        assertEquals(56.25, Double.parseDouble(getItemByName("math")), 0.1, "Math is incorrect");
I would provide a more specific error message

2022-03-17 02:46 UTC, Hedgemon4 commented on src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
> +        assertEquals(56.25, Double.parseDouble(getItemByName("growthRate")), 0.1, "Math is incorrect. Refer back to the question for what the correct calculation should look like");
I would say something more along the lines of growthRate is incorrect, but I think that is a personal preference.

2022-03-17 02:46 UTC, Hedgemon4 approved these changes

2022-03-18 19:33 UTC, aadiraju submitted a review, later dismissed
Looks good! @Opeyem1a can look at it and merge it in!

2022-03-18 20:14 UTC, Opeyem1a requested changes

2022-03-18 20:14 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/hard/q9/MainTest.java
> +        assertEquals(56.25, Double.parseDouble(getItemByName("growthRate")), 0.1, "Growth rate calculation is incorrect. Refer back to the question for what the correct calculation should look like")
I think delta could be `0.01` here

2022-03-20 01:34 UTC, Opeyem1a approved these changes

2022-03-25 20:17 UTC, Opeyem1a approved these changes

2022-04-01 22:50 UTC, merged