oop-special_class_method-medium-q4
canvas-gamification/canvas-gamification-junit-tests pull request #635
Opened 2023-05-04 18:39 UTC by KaiKhademi

## PR Checklist
- [x]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [x]  Are the assertion fail messages good?
    - [x]  Logical (does it make sense?)
    - [x]  Readable (can a student understand what’s wrong?)
    - [x]  Not too feed-y (does it give away the answer?)
    - [x]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [x]  Specific (does the fail message relate to the question?)
- [x]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [x]  EOF newlines
- [x]  Do the comments for Parsons follow the correct convention?
- [x]  Is the question being tested sufficiently?
    - [x]  Are there representative cases to test the program?
    - [x]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [x]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-17 02:06 UTC, SamamthaH requested changes

2023-06-17 02:06 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +    public void correctSetSizeMethod(String initialValue, String updatedValue) throws Throwable {
```suggestion
    public void correctSetBreedMethod(String initialValue, String updatedValue) throws Throwable {
```

2023-06-17 02:06 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +    public void correctGetSetMethods(String initialValue, String updatedValue) throws Throwable {
```suggestion
    public void plantMethodsWorkCorrectlyWorkTogether(String initialValue, String updatedValue) throws Throwable {
```

2023-06-17 02:06 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +        testClass.callMethod(setAttributeMethodName, setMethodArguments, testInstance);
we might want another assert before this to split the fail message for incorrect name and incorrect arguments

2023-06-28 20:58 UTC, SamamthaH requested changes

2023-06-28 20:58 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/QuestionText.md
> +    - It is not visible from another class.
```suggestion
    - It is visible from another class.
```

2023-06-28 20:58 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/QuestionText.md
> +    - a `toString` method which return the string `"My breed is " + x` where x is the value of **breed**
```suggestion
    - a `toString` method which return the string `"My breed is x"` where x is the value of **breed**
```

2023-06-28 20:58 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +        assertTrue((testClass.hasMethod(setAttributeMethodName, methodModifierClasses)),
this will never be failed since it will never be reaches past the visibility assert

2023-06-28 20:58 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +        _assertEquals(updatedValue, getMethodOutput, errorMessage);
there should also be an assert for toString

2023-07-12 01:51 UTC, SamamthaH requested changes

2023-07-12 01:51 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +        testClass.callMethod(setAttributeMethodName, setMethodArguments, testInstance);
This should be moved the the first hasMethod assert

2023-07-12 01:51 UTC, SamamthaH commented on src/oop/special_class_method/medium/q4/MainTest.java
> +                "Your " + setAttributeMethodName + " does nor have the correct parameters.");
```suggestion
                "Your " + setAttributeMethodName + " does not have the correct parameters.");
```

2023-09-05 15:51 UTC, Hedgemon4 requested changes
Please address Sam's requested changes

2023-09-18 16:24 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q4/QuestionText.md
> +also includes an accessor and a mutator for each attribute.
You can remove this information about the attributes from the question header.

2023-09-18 16:24 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q4/QuestionText.md
> +    - It is visible from another class.
```suggestion
```

2023-09-18 16:25 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q4/QuestionText.md
> +    - a `setBreed` method which accepts a `String` and uses it to set the value of the **breed** attribute
Please indicate what the return types of the `set` methods should be

2023-09-26 16:19 UTC, Hedgemon4 approved these changes

2023-09-26 16:19 UTC, merged