oop-special_class_method-medium-q5
canvas-gamification/canvas-gamification-junit-tests pull request #636
Opened 2023-05-04 19:03 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-17 02:36 UTC, SamamthaH requested changes

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +
add something here or in MainTest describing what kind of question this is

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +Your `Calculator` class must have the following items
change this to reflect that this stuff will be provided

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +      initialize the **sum** and **isCorrect** attributes with **sum** being 7 times of the input value.
```suggestion
      initialize the **sum** and **isCorrect** attributes with **sum** being 7 multiplied by the input value.
```

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +    - a `toString` method which returns the string `"The sum is " + sum + " and it is " + isCorrect`
use x y formatting

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +    }
there should be a methods work together test here

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not return the value of the size attribute.");
```suggestion
                "Your " + getAttributeMethodName1 + " method does not return the value of the " + attributeName1 + " attribute.");
```

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +                "Your " + getAttributeMethodName2 + " method does not return the value of the size attribute.");
```suggestion
                "Your " + getAttributeMethodName2 + " method does not return the value of the " + attributeName2 + " attribute.");
```

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setAttributeMethodName1, setMethodArguments, testInstance);
We should probably have two separate tests for the method name and the arguments for better error messages

2023-06-17 02:36 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setAttributeMethodName2, setMethodArguments, testInstance);
this should also probably be split into two tests

2023-06-28 21:11 UTC, SamamthaH requested changes

2023-06-28 21:11 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +    - a `toString` method which returns the string `"The sum is " + x + " and it is " + y` where x is the value
```suggestion
    - a `toString` method which returns the string `"The sum is  x and it is y"` where x is the value
```

2023-06-28 21:11 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName1, testInstance);
no need for 187-192, getting without first setting has already been tested previously

2023-06-28 21:11 UTC, SamamthaH commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setAttributeMethodName1, "method should not return any output"));
no need for the assertNull either since that will have been caught already

2023-07-12 02:09 UTC, SamamthaH submitted a review, later dismissed

2023-08-04 00:43 UTC, Hedgemon4 requested changes

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +It's April fool's day and you want to change how the calculator works, so you can trick your Math teacher. Make a Java
Please remove this extra information

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/QuestionText.md
> +    - a `setSum` method which accepts a `double` and uses it to set the value of the **sum** attribute
And specify that the setters should have a void return

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName1, testInstance);
Please check that the method exists before calling it

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        assertTrue(testClass.hasModifier(setAttributeMethodName1, methodModifierClasses, "public"),
Check the return type using the hasReturnType assert before calling the method.

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setAttributeMethodName1, "method should not return any output"));
Don't this approach

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        assertTrue(testClass.hasModifier(getAttributeMethodName2, null, "public"),
Check method exists before calling it

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        };
Check return type before calling it

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +        };
Check existence of method

2023-08-04 00:43 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q5/MainTest.java
> +    public void methodsWorkingTogether(double value1, boolean value2) throws Throwable {
For this test, I think it makes more sense to call the setter and then the getter

2023-08-27 16:45 UTC, Hedgemon4 approved these changes

2023-08-27 16:45 UTC, merged