oop-special_class_method-medium-q6
canvas-gamification/canvas-gamification-junit-tests pull request #637
Opened 2023-05-04 19:57 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-18 00:43 UTC, SamamthaH requested changes

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/Scissors.java
> +        ;
```suggestion
```

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +    }
there should be a methods work together test

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not return the value of the size attribute.");
```suggestion
                "Your " + getAttributeMethodName1 + " method does not return the value of the " + attributeName1 + " attribute.");
```

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setAttributeMethodName1, setMethodArguments, testInstance);
this should probably be split into a correct name assert and a correct arguments assert

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +                "Your " + getAttributeMethodName2 + " method does not return the value of the size attribute.");
```suggestion
                "Your " + getAttributeMethodName2 + " method does not return the value of the " + attributeName2 + " attribute.");
```

2023-06-18 00:43 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setAttributeMethodName2, setMethodArguments, testInstance);
this should also be split into two asserts

2023-06-29 03:39 UTC, SamamthaH requested changes

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/QuestionText.md
> +two attributes called **isSharp** and **canCut**. This class has a constructor that initializes the two attributes,
```suggestion
two attributes called **isSharp** and **outOfReach**. This class has a constructor that initializes the two attributes,
```

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/QuestionText.md
> +      **isSharp** and **canCut** attributes in that order.
```suggestion
      **isSharp** and **outOfReach** attributes in that order.
```

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/QuestionText.md
> +    - a `setOutOfReacht` method which accepts a `boolean` and uses it to set the value of the **outOfReach** attribute
```suggestion
    - a `setOutOfReach` method that accepts a `boolean` and uses it to set the value of the **outOfReach** attribute
```

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/QuestionText.md
> +    - a `toString` method which returns the string `"isSharp is " + isSharp + " and outOfReach is " + outOfReach`
```suggestion
    - a `toString` method which returns the string `"isSharp is x and outOfReach is y"` where x is the isSharp attribute and y is the outOfReach attribute.
```

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/Scissors.java
> +    public Scissors(boolean isp, boolean cct) {
since we give this constructor to the user, I feel like cct should get changed to something more relevant to outOfReach

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName1, testInstance);
no need to test the get methods before the set methods are called since the get specific tests will have covered that

2023-06-29 03:39 UTC, SamamthaH commented on src/oop/special_class_method/medium/q6/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setAttributeMethodName1, "method should not return any output"));
also no need for the assertNulls for the same reason

2023-07-12 02:16 UTC, SamamthaH approved these changes

2023-08-04 00:43 UTC, Hedgemon4 requested changes
See feedback on other questions in this category

2023-08-27 16:51 UTC, Hedgemon4 approved these changes

2023-08-27 16:51 UTC, merged