oop-special_class_method-medium-q8
canvas-gamification/canvas-gamification-junit-tests pull request #645
Opened 2023-05-11 02:21 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-17 02:54 UTC, SamamthaH requested changes

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not return the value of the size field.");
```suggestion
                "Your " + getAttributeMethodName1 + " method does not return the value of the " + attributeName1 + " attribute.");
```

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not return the value of the size field.");
also change any other instances of field to attribute

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/QuestionText.md
> +One Piece who ate the devil fruit to gain a special ability. Make a Java class called **Luffy** that has several
```suggestion
One Piece who ate the devil fruit to gain a special ability. Make a Java class called **Luffy** that has  
```

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/QuestionText.md
> +      **skill** and **bounty** fields.
change the "field" to "attribute" in this file as well

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/QuestionText.md
> +Your `Luffy` class must have the following items
change this to reflect that the following things will have been provided

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/QuestionText.md
> +    - a `toString` method which returns the string `"My special skill is " + skill + " and my bounty is " + bounty`.
use x y format

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +}
EOF line

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +    public void correctGetNickelMethod(String skill, int bounty) throws Throwable {
```suggestion
    public void correctGetBountyMethod(String skill, int bounty) throws Throwable {
```

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +                "Your " + getAttributeMethodName2 + " method does not return the value of the size field.");
```suggestion
                "Your " + getAttributeMethodName2 + " method does not return the value of the " + attributeName2 + " attribute.");
```

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +        testClass.callMethod(setAttributeMethodName1, setMethodArguments, testInstance);
this should probably be two tests, one for name and one for arguments

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +        testClass.callMethod(setAttributeMethodName2, setMethodArguments, testInstance);
this should probably be two tests, one for name and one for arguments

2023-06-17 02:54 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +    @ParameterizedTest
I'd say combine this and the second one into one methods work together tests that also includes the toString

2023-06-29 19:01 UTC, SamamthaH requested changes

2023-06-29 19:01 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +        _assertEquals(value1, testClass.getFieldValue(testInstance, attributeName1),
this should instead be using the get method

2023-06-29 19:01 UTC, SamamthaH commented on src/oop/special_class_method/medium/q8/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setAttributeMethodName1, "method should not return any output"));
testing for no returned output should not happen here

2023-07-12 18:17 UTC, SamamthaH approved these changes

2023-08-04 00:44 UTC, Hedgemon4 requested changes
See feedback on other questions in this category

2023-08-27 17:07 UTC, Hedgemon4 approved these changes

2023-08-27 17:07 UTC, merged