oop-special_class_method-medium-q9
canvas-gamification/canvas-gamification-junit-tests pull request #647
Opened 2023-05-11 02:53 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-18 01:26 UTC, SamamthaH requested changes

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/QuestionText.md
> +
mark either in here on the Main Test what kind of question this is

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/QuestionText.md
> +the constructor. You will need to compose the necessary methods so that these attributes can be accessed from outside
```suggestion
the constructor. The necessary methods must be set up so that these attributes can be accessed from outside 
```

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/QuestionText.md
> +    - a `getMaker` method which returns the value stored in the **maker** field
change this and any other "field" to "attribute"

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/QuestionText.md
> +Your `Car` class must have the following items
modify this to express that the items below are provided

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/QuestionText.md
> +    - a `getTopSpeed` method which returns the value stored in the **topSpeed** field
we should consider adding a toString method here, since all the other section questions do

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not return the value of the size field.");
```suggestion
                "Your " + getAttributeMethodName1 + " method does not return the value of the " + attributeName1 + " attribute.");
```

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/MainTest.java
> +                attributeName1 + " and " + attributeName2 + " fields.";
```suggestion
                attributeName1 + " and " + attributeName2 + " attributes.";
```

2023-06-18 01:26 UTC, SamamthaH commented on src/oop/special_class_method/medium/q9/MainTest.java
> +                "Your " + getAttributeMethodName2 + " method does not return the value of the size field.");
```suggestion
                "Your " + getAttributeMethodName2 + " method does not return the value of the " + attributeName2 + " attribute.");
```

2023-06-29 20:01 UTC, SamamthaH requested changes

2023-07-12 18:20 UTC, SamamthaH approved these changes

2023-08-04 00:45 UTC, Hedgemon4 requested changes
See feedback on other questions in this category

2023-08-27 17:20 UTC, Hedgemon4 approved these changes

2023-08-27 17:20 UTC, merged