oop-special_class_method-hard-q4
canvas-gamification/canvas-gamification-junit-tests pull request #660
Opened 2023-05-16 10:24 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-05-19 04:04 UTC, SamamthaH requested changes

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setString2MethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setString2MethodName, "method should not return any output"));
```

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", setString2MethodName, "does not correctly set the value of the", String2FieldName, "field.");
```suggestion
                "Your", setString2MethodName, "method does not correctly set the value of the", String2FieldName, "attribute.");
```

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        String incorrectDoubleValueMessage =
change filed to attribute

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", getString2MethodName, "does not correctly get the value of the", String2FieldName, "field.");
```suggestion
                "Your", getString2MethodName, "method does not correctly get the value of the", String2FieldName, "field.");
```

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", setStringMethodName, "does not correctly set the value of the", StringFieldName, "field.");
```suggestion
                "Your", setStringMethodName, "method does not correctly set the value of the", StringFieldName, "field.");
```

2023-05-19 04:04 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "method should not return any output"));
```

2023-05-25 00:38 UTC, SamamthaH requested changes

2023-05-25 00:38 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "The attribute " +  string2FieldName + " could not be found in your class. Please make sure you have added it, it is spelled correctly, and has the correct type");
```suggestion
                "The attribute " +  stringFieldName + " could not be found in your class. Please make sure you have added it, it is spelled correctly, and has the correct type");
```

2023-05-25 00:38 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", getStringMethodName, "does not correctly get the value of the", stringFieldName, "field.");
```suggestion
                "Your", getStringMethodName, "method does not correctly get the value of the", stringFieldName, "attribute.");
```

2023-05-25 00:38 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", setStringMethodName, "method does not correctly set the value of the", stringFieldName, "field.");
Change this and any other instances of "field" to "attribute"

2023-05-25 00:38 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        Object[][] setBooleanArguments = {
incorrect name

2023-05-25 00:38 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +    - a `toString` method which returns a String of the information about the `Detergent` class of the form
This is an easily understandable format but for consistency we should probably try to have all the questions follow the x y format

2023-05-27 17:24 UTC, SamamthaH requested changes
I think you may have forgotten to push from your IDE since you haven't added any commits since my last review

2023-05-27 17:24 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        String incorrectDoubleValueMessage =
this should be String not double

2023-06-03 00:56 UTC, SamamthaH requested changes

2023-06-03 00:56 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its fields using its setter methods.");
```suggestion
                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```

2023-06-03 00:56 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +- Fields :
```suggestion
- Attributes:
```

2023-06-03 00:56 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +    - a `setStrength` method which is accessible from other classes, accepts a `String` value, and updates the **
I don't think the ** formatting transfers if you cut the line here

2023-06-03 00:56 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +print the toString for this class.
fix formatting and the above cutting of the ** formatting

2023-06-03 00:56 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", getString2MethodName, "method does not correctly get the value of the", string2FieldName, "field.");
```suggestion
                "Your", getString2MethodName, "method does not correctly get the value of the", string2FieldName, "attribute.");
```

2023-06-29 20:45 UTC, SamamthaH requested changes

2023-06-29 20:45 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +print the toString for this class.
fix the formatting on the line cut

2023-06-29 20:45 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +      `"The Detergent instance name is " + x + " and its strength is " + y + "."` where x is the value of the **name**
```suggestion
      `"The Detergent instance name is  x and its strength is y."` where x is the value of the **name**
```

2023-06-29 20:45 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        testClass.setFieldValue(classInstance, value, stringFieldName);
why change the field value?

2023-06-29 20:45 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        _assertEquals(initialValue, testClass.callMethod(getString2MethodName, classInstance),
no need to check the get methods before the set methods are called

2023-07-18 20:47 UTC, SamamthaH requested changes

2023-07-18 20:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        assertTrue(testClass.hasModifier(constructorClasses, "public"), incorrectConstructorVisibilityModifier);
This already gets tested in HasRequiredConstructor test

2023-07-18 20:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", className, " toString method does not return the correct String.");
```suggestion
                "Your", className, "toString method does not return the correct String.");
```

2023-07-18 20:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your " + getString2MethodName + " method does not return the correct value calling the " + setString2MethodName + " method.");
```suggestion
                "Your " + getString2MethodName + " method does not return the correct value after calling the " + setString2MethodName + " method.");
```

2023-07-18 20:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your " + getStringMethodName + " method does not return the correct value calling the " + setStringMethodName + " method.");
```suggestion
                "Your " + getStringMethodName + " method does not return the correct value after calling the " + setStringMethodName + " method.");
```

2023-07-18 20:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```suggestion
                "Your", className, "toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```

2023-08-09 02:55 UTC, SamamthaH requested changes

2023-08-09 02:55 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Test
Annotate where appropriate

2023-08-09 02:55 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    public void detergentClassHasCorrectFields() {
```suggestion
    public void detergentClassHasCorrectAttributes() {
```

2023-08-09 02:55 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +                "The attribute " +  string2FieldName + " could not be found in your class. Please make sure you have added it, it is spelled correctly.");
fix the last sentence's grammer

2023-08-09 02:55 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setString2MethodName, setSizeArguments, setMethodModifiers, classInstance);
use .hasMethod first with void.type instead of assertNull here and everywhere else

2023-08-09 02:55 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +`String` variable called **name** and another `String` variable called **strength**.
get rid of duplicated description portions

2023-08-21 03:09 UTC, SamamthaH requested changes

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Test
everything tested here is already tested in detergentClassHasCorrectSetNameMethod, so there is no need for this test

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setString2MethodName, "method should not return any output"));
this has already been checked in the above asserts

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Test
This also is duplicated asserts of the below test

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Test
Same here as others

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "method should not return any output"));
this is already tested in the above asserts

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Test
Same here as well

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    @Tag("dependent2")
```suggestion
    @Tag("dependent1")
```

2023-08-21 03:09 UTC, SamamthaH commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +    - a `setName` method which is accessible from other classes, accepts a `String` value, and updates the **name**
for set methods, include some description of the void return value

2023-09-05 15:52 UTC, Hedgemon4 requested changes
Please address the changes requested by Sam

2023-09-18 16:54 UTC, Hedgemon4 requested changes

2023-09-18 16:54 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    }
You have this test twice.

2023-09-18 16:54 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q4/MainTest.java
> +    public void setVolumeIsDefinedCorrectly() {
I don't think this should be `setVolume`

2023-10-28 04:42 UTC, Hedgemon4 requested changes

2023-10-28 04:42 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q4/QuestionText.md
> +Chemistry tells us a lot about the properties of different liquids. Write a Java class called `Detergent` with the
You should also say that you need a test class

2024-02-07 23:17 UTC, Hedgemon4 approved these changes
Looks good

2024-02-07 23:17 UTC, merged