oop-special_class_method-hard-q5
canvas-gamification/canvas-gamification-junit-tests pull request #661
Opened 2023-05-16 11:53 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-05-19 19:47 UTC, SamamthaH requested changes

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +
much of this opening paragraph is made redundant by the description of the class below

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +
change field to attributes

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +      from other classes
fix formatting here

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +      other classes
fix formatting here

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +      `"Road{lanes: " + lanes + ", typeOfRoad: " + typeOfRoad + ", maxCapacity: " + maxCapacity + "}"`.
change to the form discussed in meeting throughout question

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +Your `Test` class will have a main method which initializes a `Road` of **lanes** 3 and **typeOfRoad** "Highway",
```suggestion
Your `Test` class will have a main method which initializes a `Road` of **lanes** 3, **typeOfRoad** "Highway",
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    private final String StringFieldName = "typeOfRoad";
change variable name to start with a lowercase letter

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void chairClassHasCorrectSetTypeOfRoadMethod(String initialValue, String updatedValue) throws Throwable {
```suggestion
    public void roadClassHasCorrectSetTypeOfRoadMethod(String initialValue, String updatedValue) throws Throwable {
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void chairClassHasCorrectToStringMethod(int value1, String value2, int value3) throws Throwable {
```suggestion
    public void roadClassHasCorrectToStringMethod(int value1, String value2, int value3) throws Throwable {
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +
change field to attribute

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        String incorrectDoubleValueMessage =
change name to reflect that it is an int not a double

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", setIntMethodName, "does not correctly set the value of the", intFieldName, "field.");
```suggestion
                "Your", setIntMethodName, "method does not correctly set the value of the", intFieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setIntMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setIntMethodName, "method should not return any output"));
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", getIntMethodName, "does not correctly get the value of the", intFieldName, "field.");
```suggestion
                "Your", getIntMethodName, "method does not correctly get the value of the", intFieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", setStringMethodName, "does not correctly set the value of the", StringFieldName, "field.");
```suggestion
                "Your", setStringMethodName, "method does not correctly set the value of the", StringFieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "method should not return any output"));
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", getStringMethodName, "does not correctly get the value of the", StringFieldName, "field.");
```suggestion
                "Your", getStringMethodName, "method does not correctly get the value of the", StringFieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", setInt2MethodName, "does not correctly set the value of the", int2FieldName, "field.");
```suggestion
                "Your", setInt2MethodName, "method does not correctly set the value of the", int2FieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setInt2MethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setInt2MethodName, "method should not return any output"));
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", getInt2MethodName, "does not correctly get the value of the", int2FieldName, "field.");
```suggestion
                "Your", getInt2MethodName, "method does not correctly get the value of the", int2FieldName, "field.");
```

2023-05-19 19:47 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +
There should be another test that checks if all the methods work together properly

2023-05-27 03:26 UTC, SamamthaH requested changes

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", setIntMethodName, "method does not correctly set the value of the", intFieldName, "field.");
```suggestion
                "Your", setIntMethodName, "method does not correctly set the value of the", intFieldName, "attribute.");
```

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", setIntMethodName, "method does not correctly set the value of the", intFieldName, "field.");
Do this for all other error messages in setters and getters

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its fields using its setter methods.");
```suggestion
                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +    - a `setLanes` method which accepts a `int` value, updates the **lanes** field with it, and is accessible from
```suggestion
    - a `setLanes` method which accepts a `int` value, updates the **lanes** attribute with it, and is accessible from
```

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your " + className + " constructor does not initialize the " + intFieldName + " filed to the correct value.";
```suggestion
                "Your " + className + " constructor does not initialize the " + intFieldName + " attribute to the correct value.";
```

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +                "Your " + className + " constructor does not initialize the " + intFieldName + " filed to the correct value.";
repeat with next two lines

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void detergentClassHasRequiredConstructor() {
```suggestion
    public void roadClassHasRequiredConstructor() {
```

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        testClass.setFieldValue(classInstance, initialValue, stringFieldName);
why is this here?

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        testClass.setFieldValue(classInstance, value2, stringFieldName);
same here

2023-05-27 03:26 UTC, SamamthaH commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void detergentClassMethodsWorkTogether(int value1, String value2, int value3) throws Throwable {
```suggestion
    public void roadClassMethodsWorkTogether(int value1, String value2, int value3) throws Throwable {
```

2023-06-03 01:01 UTC, SamamthaH approved these changes

2023-08-04 03:45 UTC, SamamthaH submitted a review, later dismissed

2023-08-15 01:43 UTC, Hedgemon4 requested changes

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +**Road** that has an `int` variable called **lanes**, a `String` variable called **typeOfRoad**, and an
Please remove the attributes from this header

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +    - a `setLanes` method which accepts a `int` value, updates the **lanes** attribute with it, and is accessible from
Please mention the return type for setters.

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        outputClass.callMethod("main", arguments, methodModifiers, classInstance, new Clause[]{
I think it could be beneficial to the student if we also set a custom error message for this. That way it will be related to the question.

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setIntMethodName, "method should not return any output"));
I think it is better to use the return type assert instead of the assertNull here

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "method should not return any output"));
Same thing here with the assertNull

2023-08-15 01:43 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setInt2MethodName, "method should not return any output"));
And here

2023-08-29 00:47 UTC, Hedgemon4 requested changes

2023-08-29 00:47 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void correctTestClass() throws Throwable {
Add tags to this please

2023-08-29 00:47 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +        Object[][] arguments = {
Also, use a custom error message for the clause checking.

2023-08-29 00:47 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +Your `Road` class must have the following items:
Please add the question context back to the question.

2023-08-29 00:47 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +Your `Road` class must have the following items:
For example, for this question the document had " You are writing a Java program that describes different types of roads and their attributes. ... ". You can use this first part and then stay something similar to "Using the requirements below, write a Java class called x:

2023-09-26 16:44 UTC, Hedgemon4 requested changes

2023-09-26 16:44 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +Road the has the following description:
You should also indicate the student will need to write a test class or else they might miss it by mistake.

2023-09-26 16:44 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/MainTest.java
> +    public void roadClassHasRequiredConstructor() {
You should also add dependencies here (this is dependent on the constructor and toString).

2024-01-12 21:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q5/QuestionText.md
> +Your `Test` class will have a main method which initializes a `Road` of **lanes** 3, **typeOfRoad** "Highway",
```suggestion
Your `Test` class will have a main method which initializes a `Road` of **lanes** 3,  and with **typeOfRoad** "Highway",
```

2024-01-12 21:40 UTC, Hedgemon4 approved these changes
LGTM

2024-01-12 21:41 UTC, merged