oop-special_class_method-hard-q7
canvas-gamification/canvas-gamification-junit-tests pull request #663
Opened 2023-05-18 21:08 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-05-20 02:13 UTC, SamamthaH requested changes

2023-05-20 02:13 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        String incorrectStringValueMessage =
this should not be labelled string

2023-05-20 02:13 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your", setDoubleMethodName, "does not correctly set the value of the", doubleFieldName, "attribute.");
in this and any other messages added "method" after you say a method name

2023-05-20 02:13 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        testClass.setFieldValue(classInstance, initialValue, intFieldName);
why is this here?

2023-05-20 02:13 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        testClass.setFieldValue(classInstance, value2, intFieldName);
why is this here?

2023-05-20 02:13 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        Object[][] setBooleanArguments = {
this should not be labelled boolean

2023-06-30 02:30 UTC, SamamthaH requested changes

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/QuestionText.md
> +      `"I have " + x + " dollars in me after " + y + " days."` where x is the value of the **money** attribute
```suggestion
      `"I have x dollars in me after y days."` where x is the value of the **money** attribute
```

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setDoubleMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setDoubleMethodName, "method should not return any output"));
```

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setIntMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setIntMethodName, "method should not return any output"));
```

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/QuestionText.md
> +- Fields :
```suggestion
- Attributes:
```

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your", className, " toString method does not return the correct String.");
```suggestion
                "Your", className, "toString method does not return the correct String.");
```

2023-06-30 02:30 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        _assertEquals(initialValue, testClass.callMethod(getDoubleMethodName, classInstance),
no need to test getter methods before setters are called

2023-07-25 21:43 UTC, SamamthaH requested changes

2023-07-25 21:43 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        assertTrue(testClass.hasField(doubleFieldName, double.class),
add in the new .hasField for better error messages

2023-07-25 21:43 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your " + className + " class is missing the " + doubleFieldName + " attributes.");
```suggestion
                "Your " + className + " class is missing the " + doubleFieldName + " attribute.");
```

2023-07-25 21:43 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your " + className + " class is missing the " + intFieldName + " attributes.");
```suggestion
                "Your " + className + " class is missing the " + intFieldName + " attribute.");
```

2023-07-25 21:43 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +
There aren't asserts to check if the constructors exist, only that they initialize attributes correctly and have the correct modifier

2023-08-09 03:08 UTC, SamamthaH requested changes

2023-08-09 03:08 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        Class<?>[] constructorClasses = {double.class, int.class};
I believe this never gets used

2023-08-09 03:08 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setDoubleMethodName, setSizeArguments, setMethodModifiers, classInstance);
use .hasMethod first with void.type instead of assertNull here and everywhere else

2023-08-09 03:08 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your " + getDoubleMethodName + " method does not return the correct value calling the " + setDoubleMethodName + " method.");
```suggestion
                "Your " + getDoubleMethodName + " method does not return the correct value after calling the " + setDoubleMethodName + " method.");
```

2023-08-09 03:08 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                "Your " + getIntMethodName + " method does not return the correct value calling the " + setIntMethodName + " method.");
```suggestion
                "Your " + getIntMethodName + " method does not return the correct value after calling the " + setIntMethodName + " method.");
```

2023-08-09 03:08 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/QuestionText.md
> +**PiggyBank** that has a `double` variable called **money** and another `int` variable called **time**.
get rid of duplicate descriptions

2023-08-26 01:54 UTC, SamamthaH requested changes

2023-08-26 01:54 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    @Tag("dependent2")
change to "dependency1"

2023-08-26 01:54 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    public void setMoneyIsDefinedCorrectly() {
I don't believe this and all the following "isDefinedCorrectly" methods are necessary

2023-08-26 01:54 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    @Tag("dependent2")
```suggestion
    @Tag("dependent1")
```

2023-08-26 01:54 UTC, SamamthaH commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    @Tag("dependent1")
i don't believe we are currently adding tags to constructors

2023-09-05 16:03 UTC, Hedgemon4 requested changes
Please address the changes Sam requested

2023-09-26 17:23 UTC, Hedgemon4 requested changes

2023-09-26 17:23 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/QuestionText.md
> +
Please add question context.

2023-09-26 17:23 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    public void piggyBankClassHasRequiredConstructor() {
I think we should change the names of the constructor tests to better differentiate them.

2023-09-26 17:23 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +                Arguments.of(4535.4, 300),
Should test 0 here as well

2023-09-26 17:23 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +
I think we should also have a test that checks if the methods work with the parameterless constructor.

2024-01-12 22:02 UTC, Hedgemon4 requested changes

2024-01-12 22:02 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +        );
Should check reseting value to zero

2024-01-12 22:02 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +
You should check setting 0

2024-02-07 23:21 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/QuestionText.md
> +`PiggyBank` that has the following description:
```suggestion
`PiggyBank` based on the following description:
```

2024-02-07 23:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q7/MainTest.java
> +    }
I think this is fine, but going forward we honestly don't need this method if we test the same thing in the `xHasCorrectMethod` test as well.

2024-02-07 23:32 UTC, Hedgemon4 approved these changes

2024-02-07 23:33 UTC, merged