oop-special_class_method-hard-q8
canvas-gamification/canvas-gamification-junit-tests pull request #664
Opened 2023-05-19 16:09 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-05-20 02:36 UTC, SamamthaH requested changes

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +You are writing a Java program that details various round objects. Write a Java class called **Circle** that has a
a lot of text here is made redundant by the details in the class description

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +    - a `setRadius` method which accepts a `double` value, updates the *radius** attribute with it, and is accessible
```suggestion
    - a `setRadius` method which accepts a `double` value, updates the **radius** attribute with it, and is accessible
```

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +    - a `toString` method which returns a String of the information about the `Circle` class of the form
change this description to be more like what we discussed in meeting but the rest of the question's toString stuff can stay the same

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your", setDoubleMethodName, "does not correctly set the value of the", doubleFieldName, "attribute.");
in this and any other messages make sure a method name is followed by "method"

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        testClass.setFieldValue(classInstance, initialValue, stringFieldName);
why is this here?

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        testClass.setFieldValue(classInstance, value2, stringFieldName);
why is this here?

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        Object[][] setBooleanArguments = {
this should not be labelled boolean

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your " + getStringMethodName + " method does not return the correct value calling the " + setStringMethodName + " method.");
```suggestion
                "Your " + getStringMethodName + " method does not return the correct value after calling the " + setStringMethodName + " method.");
```

2023-05-20 02:36 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your " + getDoubleMethodName + " method does not return the correct value calling the " + setDoubleMethodName + " method.");
```suggestion
                "Your " + getDoubleMethodName + " method does not return the correct value after calling the " + setDoubleMethodName + " method.");
```

2023-06-30 02:41 UTC, SamamthaH requested changes

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +      `"I have a " + x + " radius and my colour is " + y` where x is the value of **radius** attribute and y is the
```suggestion
      `"I have a x radius and my colour is y"` where x is the value of **radius** attribute and y is the
```

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setDoubleMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setDoubleMethodName, "method should not return any output"));
```

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setStringMethodName, "method should not return any output"));
```

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your", className, " toString method does not return the correct String.");
```suggestion
                "Your", className, "toString method does not return the correct String.");
```

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your " + className + " class is missing the " + doubleFieldName + " attributes.");
change attributes from plural to singular in this message and the one on line 63

2023-06-30 02:41 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        _assertEquals(initialValue, testClass.callMethod(getDoubleMethodName, classInstance),
no need for testing get before set

2023-07-25 22:16 UTC, SamamthaH requested changes

2023-07-25 22:16 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +    @Test
modify to include the new hasField method

2023-07-25 22:16 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +
There is no assert checking if the constructor exists, only that it initializes the attributes properly, and then that it has the correct visibility

2023-07-25 22:16 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```suggestion
                "Your", className, "toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```

2023-07-25 22:16 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +    - A constructor which is accessible from other classes and accepts a`double` and a `String` to initialize the
```suggestion
    - A constructor which is accessible from other classes and accepts a `double` and a `String` to initialize the
```

2023-07-25 22:16 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +    - a `setColour` method which accepts an `int` value, updates the **colour** attribute with it, and is accessible
```suggestion
    - a `setColour` method which accepts a `String` value, updates the **colour** attribute with it, and is accessible
```

2023-08-09 03:19 UTC, SamamthaH requested changes

2023-08-09 03:19 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +    @Test
Annotate where appropriate

2023-08-09 03:19 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        assertTrue(testClass.hasModifier(constructorClasses, "public"), incorrectConstructorVisibilityModifier);
this is already tested elsewhere

2023-08-09 03:19 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        Object setMethodOutput = testClass.callMethod(setDoubleMethodName, setSizeArguments, setMethodModifiers, classInstance);
use .hasMethod first with void.type here and everywhere else

2023-08-09 03:19 UTC, SamamthaH commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +`double` variable called **radius** and another `String` variable called **colour**.
get rid of duplicated description

2023-09-05 16:18 UTC, Hedgemon4 requested changes

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +Your `Circle` class must have the following items:
Please add back question context

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +- Methods:
Please mention that the `set` methods should not return anything

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +Your `Test` class will have a main method which initializes a `Circle` of **radius** 3.75 and **colour** "Red". Then,
Please add some more context to this description, and include the file name for the test class.

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +    public void correctTestClass() throws Throwable {
The main method here should be **dependency1**, and all methods it is dependent on should have the tag **dependent1**

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        Object[][] arguments = {
Please also add a custom error message for calling the main method.

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                "Your " + className + " constructor does not have the correct modifier.");
```suggestion
                "Your " + className + " constructor does not have the correct visibility modifier.");
```

2023-09-05 16:18 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        assertTrue(testClass.hasModifier(constructorClasses, "public"), incorrectConstructorVisibilityModifier);
I think this is redundant as you already test it in the other test method.

2023-09-26 17:31 UTC, Hedgemon4 requested changes

2023-09-26 17:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/QuestionText.md
> +description:
Please also add some context for the test class.

2023-09-26 17:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        _assertEquals(setValue, testClass.getFieldValue(classInstance, doubleFieldName), incorrectSetMethodMessage);
You should use the assert with the delta here so that if the number is slightly off, the student does not get docked marks.

2023-09-26 17:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +        _assertEquals(setValue, testClass.getFieldValue(classInstance, doubleFieldName), incorrectSetMethodMessage);
This goes for all asserts with a double.

2023-09-26 17:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +                Arguments.of(4535.4, 432.2),
Should also test zero here.

2023-09-26 17:31 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q8/MainTest.java
> +    @Tag("dependent2")
```suggestion
    @Tag("dependent1")
```

2024-01-17 20:16 UTC, Hedgemon4 approved these changes
Looks good. Good work Kai.

2024-01-17 20:17 UTC, merged