oop-object_interactions-hard-q3
canvas-gamification/canvas-gamification-junit-tests pull request #671
Opened 2023-05-28 20:28 UTC by SamamthaH

## PR Checklist
- [x]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [x]  Are the assertion fail messages good?
    - [x]  Logical (does it make sense?)
    - [x]  Readable (can a student understand what’s wrong?)
    - [x]  Not too feed-y (does it give away the answer?)
    - [x]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [x]  Specific (does the fail message relate to the question?)
- [x]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [x]  EOF newlines
- [x]  Do the comments for Parsons follow the correct convention?
- [x]  Is the question being tested sufficiently?
    - [x]  Are there representative cases to test the program?
    - [x]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [x]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-19 08:01 UTC, KaiKhademi requested changes

2023-07-10 21:37 UTC, KaiKhademi requested changes

2023-07-10 21:37 UTC, KaiKhademi commented on src/oop/object_interactions/hard/q3/MainTest.java
> +                String.format("Your %s class constructor has the incorrect visibility modifier.", objectClassName));
Put these two in a separate test, we need to give grade just for writing constructor as well

2023-08-24 21:12 UTC, Hedgemon4 submitted a review, later dismissed

2023-08-24 21:12 UTC, Hedgemon4 commented on src/oop/object_interactions/hard/q3/QuestionText.md
> +a `BloodDonor` class using the requirements below, and create a `canReceiveBloodFrom` method that checks if the
Remove the stuff about the method please.

2023-08-24 21:13 UTC, Hedgemon4 approved these changes

2023-08-24 21:13 UTC, merged