oop-object_independence-medium-q5
canvas-gamification/canvas-gamification-junit-tests pull request #675
Opened 2023-05-30 18:00 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-02 01:30 UTC, SamamthaH requested changes

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/QuestionText.md
> +    - A single constructor with parameters of a `String` and an `itn` that initialises the **name** and
```suggestion
    - A single constructor with parameters of a `String` and an `int` that initializes the **name** and
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/QuestionText.md
> +      `"Team " + name + " has won " + totalWins + " games"` and is visible from other classes.
change this to be the x y formatting for consistency

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +    // Parsons question
incorrect formatting

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +        String bankString = "oop.object_independence.medium.q5." + className;
incorrect name

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + className + " class is missing the " + firstFieldName + " attributes.");
```suggestion
                "Your " + className + " class is missing the " + firstFieldName + " attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + firstFieldName + " does not have the correct visibility modifier.");
```suggestion
                "Your " + firstFieldName + " attribute does not have the correct visibility modifier.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + className + " class is missing the " + secondFieldName + " attributes.");
```suggestion
                "Your " + className + " class is missing the " + secondFieldName + " attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + secondFieldName + " does not have the correct visibility modifier.");
```suggestion
                "Your " + secondFieldName + " attribute does not have the correct visibility modifier.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +        assertTrue(testClass.hasConstructor(constructorClasses, new String[]{"public"}),
this already gets checked above

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + className + " constructor does not correctly initialize the " + firstFieldName + " field.");
```suggestion
                "Your " + className + " constructor does not correctly initialize the " + firstFieldName + " attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + className + " constructor does not correctly initialize the " + secondFieldName + " field.");
```suggestion
                "Your " + className + " constructor does not correctly initialize the " + secondFieldName + " attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your", getSecondField, "does not correctly get the value of the", secondFieldName, "attribute.");
```suggestion
                "Your", getSecondField, "method does not correctly get the value of the", secondFieldName, "attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your", setSecondField, "does not correctly set the value of the", secondFieldName, "attribute.");
```suggestion
                "Your", setSecondField, "method does not correctly set the value of the", secondFieldName, "attribute.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +        assertNull(setMethodOutput, String.join(" ", "Your", setSecondField, "should not return any output"));
```suggestion
        assertNull(setMethodOutput, String.join(" ", "Your", setSecondField, "method should not return any output"));
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your " + getSecondField + " method does not return the correct value calling the " + setSecondField + " method.");
```suggestion
                "Your " + getSecondField + " method does not return the correct value after calling the " + setSecondField + " method.");
```

2023-06-02 01:30 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter methods.");
```suggestion
                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter method.");
```

2023-07-06 03:06 UTC, SamamthaH requested changes

2023-07-06 03:06 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your", className, " toString method does not return the correct String.");
```suggestion
                "Your", className, "toString method does not return the correct String.");
```

2023-07-06 03:06 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +                "Your", className, " toString method does not return the correct String after updating the values of its attributes using its setter method.");
```suggestion
                "Your", className, "toString method does not return the correct String after updating the values of its attributes using its setter method.");
```

2023-07-25 23:17 UTC, SamamthaH requested changes

2023-07-25 23:17 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +    // Java
In this comment https://github.com/canvas-gamification/canvas-gamification-junit-tests/pull/675#discussion_r1213821504 I asked you to fix the formatting on the parsons comment, however you switched it to Java instead. Is there another reason for the switch?

2023-07-25 23:17 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +    public void teamClassHasRequiredFields() {
```suggestion
    public void teamClassHasRequiredAttributes() {
```

2023-07-25 23:17 UTC, SamamthaH commented on src/oop/object_independence/medium/q5/MainTest.java
> +    @Test
modify to include new hasField method

2023-07-26 21:25 UTC, KaiKhademi commented on src/oop/object_independence/medium/q5/MainTest.java
> +    // Java
Same reason as the last prs

2024-02-13 21:56 UTC, Hedgemon4 requested changes

2024-02-13 21:56 UTC, Hedgemon4 commented on src/oop/object_independence/medium/q5/QuestionText.md
> +where you keep track of the teams in the league and the games they have won as attribute.
```suggestion
where you keep track of the teams in the league and the games they have won as attribute using the description below.
```

2024-02-13 21:56 UTC, Hedgemon4 commented on src/oop/object_independence/medium/q5/QuestionText.md
> +    - Note that all setter methods must not return any value
As there is not multiple setter methods, I would just add this point to the setter method description.

2024-02-13 21:56 UTC, Hedgemon4 commented on src/oop/object_independence/medium/q5/MainTest.java
> +                Arguments.of(10, 20),
Should also test if you pass the same value that it already is, as well as setting the value to 0 and setting the value from 0 to another number.

2024-02-26 02:00 UTC, Hedgemon4 approved these changes

2024-02-26 02:01 UTC, merged