oop-static_modifier-medium-q2
canvas-gamification/canvas-gamification-junit-tests pull request #678
Opened 2023-06-07 01:27 UTC by SamamthaH

## PR Checklist
- [x]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [x]  Are the assertion fail messages good?
    - [x]  Logical (does it make sense?)
    - [x]  Readable (can a student understand what’s wrong?)
    - [x]  Not too feed-y (does it give away the answer?)
    - [x]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [x]  Specific (does the fail message relate to the question?)
- [x]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [x]  EOF newlines
- [x]  Do the comments for Parsons follow the correct convention?
- [x]  Is the question being tested sufficiently?
    - [x]  Are there representative cases to test the program?
    - [x]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [x]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-06-07 21:10 UTC, SamamthaH commented on src/oop/static_modifier/medium/q2/QuestionText.md
> +    - A contractor that calls the `incrementer` method to initialize the **identification** attribute of the `Laptop`
```suggestion
    - A constructor that calls the `incrementer` method to initialize the **identification** attribute of the `Laptop`
```

2023-08-24 21:28 UTC, Hedgemon4 requested changes

2023-08-24 21:28 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q2/QuestionText.md
> +    - A static `int` attribute called **initial** which is used to assign new **identification** numbers
We should note somewhere that this is initialized to zero.

2023-08-24 21:28 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q2/MainTest.java
> +            classInstance.setFieldValue(null, initialStart, intAttribute2);
We should not set this here as we want to make sure that the student is setting the initial value of this attribute to zero. You may have to order the tests so this one runs before some of the other ones. If you are not sure how to do that, take a look at #694.

2023-09-02 01:06 UTC, merged