oop-static_modifier-medium-q5
canvas-gamification/canvas-gamification-junit-tests pull request #696
Opened 2023-07-18 03:43 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-07-28 23:45 UTC, SamamthaH requested changes

2023-08-13 05:12 UTC, SamamthaH requested changes

2023-08-13 05:12 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    @Tag("dependent1")
according to Seth's example this should be "dependency1"

2023-08-13 05:12 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +    - Note that all attributes in this class are private
this should not be plural

2023-08-13 05:12 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +called **Hat** that has a static variable called **companyLogo** that is shared by all the objects of the class.
get rid of all duplicate class info

2023-09-06 16:52 UTC, Hedgemon4 requested changes

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +called **Hat**.
```suggestion
called **Hat**  to model the hats you have in the store using the requirements below:
```

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +    - A `String` attribute called **companyLogo** that has its value, initially `Nike`, shared by all **Hat** instances.
Can we call this **companyName** instead of **companyLogo**?

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    public void correctToStringMethod(String colour) throws Throwable {
You should test this with different company names.

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +                String.format(incorrectStaticError, staticAttributeName));
I would test in this method that the company name is initialized correctly, not in a separate test.

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    }
I don't think this test is necessary.

2023-09-06 16:52 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    public void correctToStringMethod(String colour) throws Throwable {
To do this you will also probably have to order the tests. See #694 for an example if you need it.

2024-03-07 19:21 UTC, Hedgemon4 requested changes
See comments

2024-03-07 19:21 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +    - Note that all attributes in this class should be private
Just add to the attribute description that it should not be visible to other classes. Having this note doesn't really make sense when there is only one attribute they are adding.

2024-03-07 19:21 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    public void hatClassHasCorrectAttributes() {
I think this test should likely come first. You should check here that the value of `companyName` is "Nike" before doing anything else. The test class could change this value for some reason.

2024-03-07 19:21 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +        String expected = "This is a " + compName + " that is " + colour + " in colour";
You should use a formatted string and put this at the top of the class so we can vary it on the website.

2024-03-07 19:21 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q5/MainTest.java
> +                Arguments.of("Black", "Nike"),
Add empty string as a test case.

2024-03-17 23:49 UTC, SamamthaH requested changes

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +    ObjectTest testClass;
add a comment about the question type

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +called **Hat**  to model the hats you have in the store using the requirements below:
```suggestion
As the manager of a local apparel store, you are tasked with modeling your store's selection. Write a Java program
called `Hat`  to model the hats you have in the store using the requirements below. Then write a class called `Test` to test `Hat` based on the second set of requirements below.
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +    - A `String` attributes called **colour** that cannot be accessed in other classes
```suggestion
    - A `String` attribute called **colour** that cannot be accessed in other classes
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +Your `Hat` class already the following items:
```suggestion
Your `Hat` class already has the following items:
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +- Methods:
make a note of visibility

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +      value of **colour** attribute
```suggestion
    - a `toString` method which returns a String of the information about the `Hat` class in the form
      `This is a x Hat that is y in colour` where x is the value of the **companyName** attribute and y is the
      value of the **colour** attribute
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +Your `Test` class will have a main method which initializes a `Hat` of **colour** value of `"Green"`. Then,
```suggestion
Your `Test` class should have a main method which initializes a `Hat` object of **colour** value of `"Green"`. Then,
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +print the toString for this class.
```suggestion
print the object on its own line using the toString method.
```

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +                    String.format(modificationErrorMessage, attributeName));
this section checks the constructor so it should have its own error message

2024-03-17 23:49 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +        outputClass.callMethod("main", arguments, methodModifiers, classInstance, new Clause[]{
write an error message for this

2024-04-07 21:20 UTC, SamamthaH requested changes

2024-04-07 21:20 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +                String.format(incorrectStaticError, staticAttributeName));
test that the static value is initialized correctly

2024-04-07 21:20 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/MainTest.java
> +                new StringLiteral("This is a " + initialName + " that is " + initialColour + " in colour"),
use attributeName instead of "colour" here for easier varying on the website

2024-04-07 21:20 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +called `Hat`  to model the hats you have in the store using the requirements below. Then write a class called `Test` to
```suggestion
called `Hat` to model the hats you have in the store using the requirements below. Then write a class called `Test` to
```

2024-04-07 21:20 UTC, SamamthaH commented on src/oop/static_modifier/medium/q5/QuestionText.md
> +      class in the form `This is a x Hat that is y in colour` where x is the value of the **companyName** attribute and
modify the strings elsewhere to match this format. Currently none of the others say "Hat" in them

2024-06-11 21:41 UTC, merged