oop-static_modifier-medium-q6
canvas-gamification/canvas-gamification-junit-tests pull request #697
Opened 2023-07-18 08:02 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-07-29 00:04 UTC, SamamthaH requested changes

2023-07-29 00:04 UTC, SamamthaH commented on src/oop/static_modifier/medium/q6/MainTest.java
> +                "Black", "Blue", "Red", "Brown", "Hello there", "It is hot", "How is the weather", "How's your day?"
you could split this into two input providers so that you could hardcode the answers instead of using the same methods as the answer

2023-08-13 05:28 UTC, SamamthaH commented on src/oop/static_modifier/medium/q6/QuestionText.md
> +You need to add the following items.
```suggestion
You need to add the following items:
```

2023-08-13 05:34 UTC, SamamthaH submitted a review, later dismissed

2023-09-06 17:02 UTC, Hedgemon4 requested changes

2023-09-06 17:02 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q6/MainTest.java
> +        assertTrue(testClass.hasModifier(methodName1, new Class<?>[]{String.class}, "public"), String.format(incorrectModifierMessage, methodName1, className));
Also check here that the method has the static modifier before calling it.

2023-09-06 17:02 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q6/MainTest.java
> +        String incorrectReturnType = "The %s method in the %s class has the incorrect return type.";
Please check for the static modifier.

2023-09-06 17:02 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q6/MainTest.java
> +                "Your", className, methodName2, "method does not return the correct String.");
```suggestion
                "Your", className, methodName2, "method does not return the original String with the vowels extracted.");
```

2023-09-06 17:02 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q6/MainTest.java
> +                "Your", className, methodName1, "method does not return the correct String.");
```suggestion
                "Your", className, methodName1, "method does not return the original String with the modified ending.");
```

2024-03-15 02:56 UTC, Hedgemon4 submitted a review, later dismissed

2024-03-15 02:56 UTC, Hedgemon4 commented on src/oop/static_modifier/medium/q6/MainTest.java
> +                "Your", className, methodName1, "method does not return the original String with the modified ending.");
```suggestion
                "Your", className, methodName1, "method does not correctly modify the end of the input string.");
```

2024-03-15 02:57 UTC, merged