oop-special_class_method-medium-q13
canvas-gamification/canvas-gamification-junit-tests pull request #701
Opened 2023-07-20 00:26 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-07-31 16:15 UTC, SamamthaH requested changes

2023-07-31 16:15 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/QuestionText.md
> +class called **Detergent** that has two attributes called **colour** and **volume**
The attributes here do not match everywhere else. However, I do think "volume" is more relevant than "colour" in which case the attributes should probably become "volume" and "manufacturer"

2023-07-31 16:15 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/MainTest.java
> +                "You have modified the provided portions of class " + className + ". Please revert them to the original state.";
this should probably be more specific on what has been modified

2023-08-14 03:30 UTC, SamamthaH requested changes

2023-08-14 03:30 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName2, testInstance);
use .hasMethod first

2023-08-14 03:30 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/MainTest.java
> +        assertTrue(testClass.hasMethod(setAttributeMethodName2, methodModifierClasses, Void.TYPE),
split this assert so return type has its own error message for clarity

2023-08-14 03:30 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/QuestionText.md
> +class called **Detergent** that has two attributes called **manufacturer** and **volume**
get rid of duplicate class information

2023-08-14 03:30 UTC, SamamthaH commented on src/oop/special_class_method/medium/q13/Detergent.java
> +    public Detergent(double c, String m) {
since we'll be giving the constructor to the students the 'c' should probably be switched to a 'v'

2023-09-07 17:08 UTC, Hedgemon4 requested changes

2023-09-07 17:08 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q13/QuestionText.md
> +    - a `setManufacturer` method which accepts a `String` and uses it to set the value of the **manufacturer** attribute
Please add the return type to the method.

2023-09-07 17:08 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q13/MainTest.java
> +        assertTrue(testClass.hasModifier(getAttributeMethodName2, null, "public"), String.format(incorrectModifierMessage, getAttributeMethodName2, className));
Please place the checks that the method is defined correctly before the call to the constructor in `createInstance()`

2023-09-07 17:08 UTC, Hedgemon4 commented on src/oop/special_class_method/medium/q13/MainTest.java
> +        assertTrue(testClass.hasReturnType(setAttributeMethodName2, new Class<?>[]{String.class}, Void.TYPE), String.format(incorrectReturnType, setAttributeMethodName2, className));
Same thing in this test.

2024-03-04 18:23 UTC, Hedgemon4 requested changes
Please look at the other questions Sam and I have given feedback on in this category and apply it to this question.

2024-06-12 20:42 UTC, merged