oop-special_class_method-medium-q14
canvas-gamification/canvas-gamification-junit-tests pull request #702
Opened 2023-07-20 01:14 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-07-31 16:21 UTC, SamamthaH requested changes

2023-07-31 16:21 UTC, SamamthaH commented on src/oop/special_class_method/medium/q14/QuestionText.md
> +      initialize the **quality** and **volume** attributes to `Good` and 1000.0.
fix line formatting

2023-07-31 16:21 UTC, SamamthaH commented on src/oop/special_class_method/medium/q14/MainTest.java
> +                "You have modified the provided portions of class " + className + ". Please revert them to the original state.";
This should probably be clearer on what has been modified

2023-08-14 03:49 UTC, SamamthaH requested changes

2023-08-14 03:49 UTC, SamamthaH commented on src/oop/special_class_method/medium/q14/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName2, testInstance);
use .hasMethod first

2023-08-14 03:49 UTC, SamamthaH commented on src/oop/special_class_method/medium/q14/MainTest.java
> +                "Your " + setAttributeMethodName2 + " method does not have the correct name, return type, or parameters.");
This assert should be split in two so return type can be its own assert

2023-08-14 03:49 UTC, SamamthaH commented on src/oop/special_class_method/medium/q14/QuestionText.md
> +Java class called **Water** that has an attribute called **quality** and another attribute called **volume**.
get rid of duplicate class details

2023-09-07 17:09 UTC, Hedgemon4 requested changes
See my feedback on the other questions in this category and apply it to this PR.

2024-03-04 18:24 UTC, Hedgemon4 requested changes
Please look at the other questions Sam and I have given feedback on in this category and apply it to this question.

2024-06-13 04:01 UTC, SamamthaH approved these changes

2024-06-13 04:01 UTC, merged