oop-special_class_method-hard-q12
canvas-gamification/canvas-gamification-junit-tests pull request #704
Opened 2023-07-20 05:09 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-08-01 03:22 UTC, SamamthaH requested changes

2023-08-01 03:22 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/QuestionText.md
> +Java class called **Laptop** that has two attributes, an `int` called **yearMade** and a `String` called **texture**
texture does not seem related to laptops

2023-08-01 03:22 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +    public void alienClassHasCorrectAttributes() {
change this and all other test titles to Laptop instead of Alien

2023-08-01 03:22 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                "Your " + className + " class is missing the " + attributeName1 + " attributes, it is spelled incorrectly.");
```suggestion
                "Your " + className + " class is missing the " + attributeName1 + " attributes, or it is spelled incorrectly.");
```

2023-08-01 03:22 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                "Your " + getAttributeMethodName1 + " method does not correctly update the value of " + setAttributeMethodName1 + " after using the " + getAttributeMethodName1 + " method.");
Fix this and the below error message. the first getAttributeMethodName and setAttributeMethodName should be replaced by setAttributeMethodName and then attributeName

2023-08-14 03:59 UTC, SamamthaH requested changes

2023-08-14 03:59 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                "Your " + className + " class is missing the " + attributeName1 + " attributes, or it is spelled incorrectly.");
change "attributes" to singular for both variable messages

2023-08-14 03:59 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName1, testInstance);
use .hasMethod first here and everywhere else

2023-08-14 03:59 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                "Your " + setAttributeMethodName1 + " method does not have the correct name, return type, or parameters.");
split this assert into two so the return value can have it's own assert. Do this in the other set method test as well.

2023-08-14 03:59 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/QuestionText.md
> +that are initialized by the constructor
get rid of duplicate class information

2023-08-14 03:59 UTC, SamamthaH commented on src/oop/special_class_method/hard/q12/QuestionText.md
> +    - a `Laptop` constructor that is visible to other classes and accepts an `int` and a `String` and uses it to initialize
```suggestion
    - a `Laptop` constructor that is visible to other classes and accepts an `int` and a `String` and uses them to initialize
```

2023-09-08 15:33 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/QuestionText.md
> +Java class called **Laptop**.
```suggestion
Java class called **Laptop** to model an object using the requirements below:
```

2023-09-08 15:38 UTC, Hedgemon4 requested changes

2023-09-08 15:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/QuestionText.md
> +    - a `getColour` method which returns the value stored in the **colour** attribute
Specify the return type for set methods.

2023-09-08 15:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +        Object testInstance = testClass.createInstance(arguments);
Move this call below the method check.

2023-09-08 15:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +        Object testInstance = testClass.createInstance(arguments);
Same thing here.

2023-09-08 15:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +        Object testInstance = testClass.createInstance(instantiationArguments);
And here

2023-09-08 15:38 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +    }
I would call the set method before the get method here, not the other way around.

2024-03-15 03:04 UTC, Hedgemon4 requested changes

2024-03-15 03:04 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +    }
You can remove the tests for "x method is defined correctly"

2024-03-15 03:04 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                Arguments.of(2020, "Red", 2021),
Should add test for setting the value to 0

2024-03-15 03:04 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                Arguments.of(3, "Red", "White"),
Should add case to set string to ""

2024-03-15 03:04 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q12/MainTest.java
> +                Arguments.of(2002, "Red"),
Should add 0 and "" as test case as you use this for the methods work together test.

2024-06-13 13:59 UTC, merged