oop-special_class_method-hard-q14
canvas-gamification/canvas-gamification-junit-tests pull request #706
Opened 2023-07-20 08:58 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-07-31 18:49 UTC, SamamthaH requested changes

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +    - These are not visible from other classes
make this singular not plural

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +    private boolean isFull;
this line is already used in the solution

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +    - These methods must be visible from other classes.
there should be a toString method described here

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +    public void alienClassHasCorrectAttributes() {
```suggestion
    public void bottleClassHasCorrectAttributes() {
```

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +                "Your " + className + " class is missing the " + attributeName + " attributes, or it is spelled incorrectly.");
```suggestion
                "Your " + className + " class is missing the " + attributeName + " attribute, or it is spelled incorrectly.");
```

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +    public void correctSetYearMadeMethod(boolean initialiValue, boolean updatedValue) throws Throwable {
```suggestion
    public void correctSetIsFullMethod(boolean initialiValue, boolean updatedValue) throws Throwable {
```

2023-07-31 18:49 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +                "Your " + getAttributeMethodName + " method does not correctly update the value of " + setAttributeMethodName + " after using the " + getAttributeMethodName + " method.");
```suggestion
                "Your " + getAttributeMethodName + " method does not correctly return the value of " + attributeName + " after using the " + setAttributeMethodName + " method.");
```

2023-08-14 04:18 UTC, SamamthaH requested changes

2023-08-14 04:18 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +        Object getMethodOutput = testClass.callMethod(getAttributeMethodName, testInstance);
use .hasMethod first

2023-08-14 04:18 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/MainTest.java
> +                "Your " + setAttributeMethodName + " method does not have the correct name, return type, or parameters.");
return type should be split into its own assert

2023-08-14 04:18 UTC, SamamthaH commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +**Bottle** that has an attribute called **isFull** which is initialized to **false** in the constructor.
get rid of duplicate class information

2023-09-08 15:40 UTC, Hedgemon4 requested changes
See feedback on other questions in this category and apply it to this PR.

2024-03-16 23:45 UTC, Hedgemon4 requested changes

2024-03-16 23:45 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +**Bottle**.
```suggestion
**Bottle** with the requirements below:
```

2024-03-16 23:45 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q14/QuestionText.md
> +    - This is not visible from other classes
```suggestion
    - A `boolean` called **isFull** that is not visible from other classes.
```

2024-03-16 23:45 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q14/MainTest.java
> +    public void getIsFullIsDefinedCorrectly() {
You can remove this test.

2024-03-16 23:45 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q14/MainTest.java
> +    public void bottleClassHasCorrectConstructor() throws Throwable {
I would do a repeated test here, just run it 3 or 5 times to make sure it is always false.

2024-03-16 23:45 UTC, Hedgemon4 commented on src/oop/special_class_method/hard/q14/MainTest.java
> +    public void setIsFullIsDefinedCorrectly() {
This can also be removed.

2024-06-14 22:32 UTC, merged