oop-programs_with_interesting_classes-easy-q4
canvas-gamification/canvas-gamification-junit-tests pull request #712
Opened 2023-08-08 19:29 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 15:54 UTC, Hedgemon4 requested changes

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +Life is a beautiful thing, and as time passes, things grow. Write a Java class about plants called `Tree`.
```suggestion
Life is a beautiful thing, and as time passes, things grow. Write a Java class about plants called `Tree` to model a plant with the requirements below:
```

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +    - A accessor and mutator methods for the **size** attribute called `getSize` and `setSize`.
I think we should change this wording so we are consistent with the rest of the questions.

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +    - A accessor and mutator methods for the **size** attribute called `getSize` and `setSize`.
Also please include the return type for the `set` methods

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +public class MainTest {
Can you please add the label that this is a parsons question to the start of the test as well like we did in other categories please?

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +    }
As this is a parsons question, I think we can just combine these two tests, so you can check the method call signature and then check that the method works.

2023-09-08 15:54 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +    }
And the same for the other methods.

2024-03-17 06:43 UTC, SamamthaH requested changes

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +Life is a beautiful thing, and as time passes, things grow. Write a Java class about plants called `Tree` to model a plant with the requirements below:
```suggestion
Life is everywhere on the planet, and it is constantly changing. Write a Java class about plants called `Tree` to model a plant with the requirements below:
```

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +- Methods:
make a note of their visibility

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md
> +    - A `gettingOlder` method which addes 4 to the **size** attribute.
```suggestion
    - A `gettingOlder` method which adds 4 to the **size** attribute.
```

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +        String expected = "This is a " + value1 + " tree with " + value2 + " centimeters in diameter.";
make the string a variable at the top of the test

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +        _assertEquals(value2 + 4, testClass.getFieldValue(classInstance, attributeName2),
make the 4 number a variable at the top of the class

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +                "Your", getAttributeName1, "does not correctly get the value of the", attributeName1, "attribute.");
```suggestion
                "Your", getAttributeName1, "method does not correctly get the value of the", attributeName1, "attribute.");
```

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +                "Your", getAttributeName2, "does not correctly get the value of the", attributeName2, "attribute.");
```suggestion
                "Your", getAttributeName2, "method does not correctly get the value of the", attributeName2, "attribute.");
```

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +                "Your", setAttributeName1, "does not correctly set the value of the", attributeName1, "attribute.");
```suggestion
                "Your", setAttributeName1, "method does not correctly set the value of the", attributeName1, "attribute.");
```

2024-03-17 06:43 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q4/MainTest.java
> +                "Your", setAttributeName2, "does not correctly set the value of the", attributeName2, "attribute.");
```suggestion
                "Your", setAttributeName2, "method does not correctly set the value of the", attributeName2, "attribute.");
```

2024-03-17 18:39 UTC, Hedgemon4 requested changes
See Sam's review

2024-06-15 01:35 UTC, merged