oop-programs_with_interesting_classes-easy-q5
canvas-gamification/canvas-gamification-junit-tests pull request #713
Opened 2023-08-11 19:41 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:02 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q5/QuestionText.md
> +program that mimics a social media platform called `Discord`.
```suggestion
program that mimics a social media platform called `Discord` and another class to test it using the requirements below:
```

2023-09-08 16:05 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                String.format(incorrectNumDays, methodName, className, attributeName1));
I think we can combine these tests as this is a parsons question.

2023-09-08 16:05 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                String.format(incorrectNumDays, methodName, className, attributeName1));
Same thing for the get/set methods below.

2023-09-08 16:06 UTC, Hedgemon4 commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +        };
Please add a custom error message for this call to the main method.

2024-03-17 07:05 UTC, SamamthaH requested changes

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                "Your", getAttributeName1, "does not correctly get the value of the", attributeName1, "attribute.");
```suggestion
                "Your", getAttributeName1, "method does not correctly get the value of the", attributeName1, "attribute.");
```

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                "Your", getAttributeName2, "does not correctly get the value of the", attributeName2, "attribute.");
```suggestion
                "Your", getAttributeName2, "method does not correctly get the value of the", attributeName2, "attribute.");
```

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                "Your", setAttributeName1, "does not correctly set the value of the", attributeName1, "attribute.");
```suggestion
                "Your", setAttributeName1, "method does not correctly set the value of the", attributeName1, "attribute.");
```

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +        Object[][] arguments = {
what is this used for?

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                "Your", setAttributeName2, "does not correctly set the value of the", attributeName2, "attribute.");
```suggestion
                "Your", setAttributeName2, "method does not correctly set the value of the", attributeName2, "attribute.");
```

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +        Object[][] arguments = {
what is this used for?

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +        String incorrectToStringMessage = String.join(" ",
make this a variable at the top of the tests

2024-03-17 07:05 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q5/MainTest.java
> +                new StringLiteral("Hello there From: Jeremy"),
make these also variables

2024-03-17 18:39 UTC, Hedgemon4 requested changes
See Sam's review

2024-06-15 19:50 UTC, merged