oop-programs_with_interesting_classes-easy-q6
canvas-gamification/canvas-gamification-junit-tests pull request #714
Opened 2023-08-11 20:09 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:06 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-17 17:42 UTC, SamamthaH requested changes

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +equipment. Make a class called `Course`.
```suggestion
University courses are expensive. Beyond tuition, there are also necessary supply costs, textbooks, and lab equipment. 
Make a class called `Course` to keep track of where the costs are coming from using the requirements below.
Then make a class called `SemesterCost` to test the `Course` class.
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +    - A `calcTotalCost` method which returns the sum of the three attributes.
make a note of the visibility of this method

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +      `calcTotalCost` and sum it for all of the courses and the print the total cost of all the courses.
```suggestion
    - In the main method initalize 5 `Course` objects and then calculate the total cost for each course using the
      `calcTotalCost` method. Sum the total cost for all the courses and then print the semester's cost.
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +### TestSocialMedia class
```suggestion
### SemesterCost Class
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +    - A `double` attribute called **textBookFee**
```suggestion
    - A `double` attribute called **textbookFee**
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/QuestionText.md
> +      to initialize the **textBookFee**, **suppliesFee**, and **labFee** attributes in that order.
```suggestion
      to initialize the **textbookFee**, **suppliesFee**, and **labFee** attributes in that order.
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/Course.java
> +    private double textBookFee;
```suggestion
    private double textbookFee;
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/MainTest.java
> +    private final String attributeName1 = "textBookFee";
```suggestion
    private final String attributeName1 = "textbookFee";
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/MainTest.java
> +    public void discordClassHasCorrectCalcTotalCostMethod(double value1, double value2, double value3) throws Throwable {
```suggestion
    public void courseClassHasCorrectCalcTotalCostMethod(double value1, double value2, double value3) throws Throwable {
```

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/MainTest.java
> +                new StringLiteral("The total cost for this semester is: 737.71 dollars"),
make this a variable at the top of the tests

2024-03-17 17:42 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q6/MainTest.java
> +                clauses);
add an error message

2024-03-17 18:39 UTC, Hedgemon4 requested changes
See Sam's review

2024-06-16 03:31 UTC, merged