oop-programs_with_interesting_classes-easy-q7
canvas-gamification/canvas-gamification-junit-tests pull request #715
Opened 2023-08-14 23:03 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:07 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-17 18:39 UTC, Hedgemon4 requested changes
See Sam's review

2024-03-17 21:54 UTC, SamamthaH requested changes

2024-03-17 21:54 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q7/MainTest.java
> +            for(int j = 0; j <= i; j ++) songs[j] = new Song((String)tests[i][0], (double)tests[i][1]);
please put this on the next line for easier readability

2024-03-17 21:54 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q7/MainTest.java
> +                    _assertEquals(songs[j].toString(), ans[j].toString(), String.format(incorrectNumDays, methodName2, className2, firstAttributeName2));
this could fail if the toString is not in place even if the method works

2024-06-17 22:03 UTC, merged