oop-programs_with_interesting_classes-easy-q8
canvas-gamification/canvas-gamification-junit-tests pull request #716
Opened 2023-08-14 23:28 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:07 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-17 22:53 UTC, SamamthaH requested changes

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/QuestionText.md
> +called `Activity` with the attributes **name**, **consumptionRate**, and **duration**
```suggestion
called `Activity` to track your water usage using the requirements below. Then make a `TestWaterConsumption` class to test `Activity`.
```

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/QuestionText.md
> +- Methods:
make note of visibility

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/QuestionText.md
> +    - A `usageCalculator` method which return the double value of **consumptionRate** times **duration**.
```suggestion
    - A `usageCalculator` method which returns a double. The returned value should be **consumptionRate** multiplied by **duration**.
```

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/QuestionText.md
> +      find the activity with the worst (highest) water consumption and then print it.
```suggestion
    - In the main method create 3 `Activity` classes and then print the sum of water consumption for all of them.
      Find the activity with the worst (highest) water consumption and then print it.
```

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/MainTest.java
> +                "Your", getAttributeName1, "does not correctly get the value of the", attributeName1, "attribute.");
```suggestion
                "Your", getAttributeName1, "method does not correctly get the value of the", attributeName1, "attribute.");
```

2024-03-17 22:53 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q8/MainTest.java
> +                new StringLiteral("The total water usage is 315.0"),
make these strings variables at the top of the tests

2024-03-18 18:38 UTC, Hedgemon4 requested changes
See Sam's review

2024-06-18 01:04 UTC, merged