oop-programs_with_interesting_classes-easy-q9
canvas-gamification/canvas-gamification-junit-tests pull request #717
Opened 2023-08-15 00:16 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:07 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-17 23:26 UTC, SamamthaH requested changes

2024-03-17 23:26 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q9/TestCarbonFootprint.java
> +        Activity a2 = new Activity("Bicycle", 10);
this is pretty nitpicky but change this so that buses have higher emissions than bicycles

2024-03-17 23:26 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q9/MainTest.java
> +        String incorrectGetMethodMessage = String.join(" ", "Your", getAttributeName1, "does not correctly get the value of the", attributeName1, "attribute.");
```suggestion
        String incorrectGetMethodMessage = String.join(" ", "Your", getAttributeName1, "method does not correctly get the value of the", attributeName1, "attribute.");
```

2024-03-17 23:26 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q9/MainTest.java
> +        String incorrectGetMethodMessage = String.join(" ", "Your", getAttributeName2, "does not correctly get the value of the", attributeName2, "attribute.");
```suggestion
        String incorrectGetMethodMessage = String.join(" ", "Your", getAttributeName2, "method does not correctly get the value of the", attributeName2, "attribute.");
```

2024-03-17 23:26 UTC, SamamthaH commented on src/oop/programs_with_interesting_classes/easy/q9/MainTest.java
> +        Clause[] clauses = {new StringLiteral("The activity that generates the most greenhouse gases is Car")};
make this string a variable at the top of the tests

2024-03-18 18:39 UTC, Hedgemon4 requested changes
See Sam's review

2024-06-18 01:48 UTC, merged