oop-static_modifier-hard-q4
canvas-gamification/canvas-gamification-junit-tests pull request #720
Opened 2023-08-15 16:56 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:49 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-18 05:06 UTC, SamamthaH requested changes

2024-03-18 05:06 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/MainTest.java
> +    @Order(3)
order this as the first test

2024-03-18 05:06 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/MainTest.java
> +    public void makeFurnitureIsDefinedCorrectly() {
this test is no longer needed

2024-03-18 05:06 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/MainTest.java
> +                clauses);
add an error message

2024-03-18 05:06 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/MainTest.java
> +                new StringLiteral("4 pieces of furniture were made"),
make this a variable at the top of the tests

2024-04-07 21:43 UTC, SamamthaH requested changes

2024-04-07 21:43 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/QuestionText.md
> +    - Note that all methods in this class should be visible from another class
"all methods" doesn't make sense when there is only one method

2024-04-07 21:43 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/QuestionText.md
> +      `Bed` object cannot be made, or subtract the **numBeams** value from the **woodBeams** and return true.
```suggestion
    - A `makeFurniture` method which returns false if the **numBeams** value is more than **woodBeams**, meaning that the
      `Bed` object cannot be made, or subtracts the **numBeams** value from the **woodBeams** and returns true.
```

2024-04-07 21:43 UTC, SamamthaH commented on src/oop/static_modifier/hard/q4/MainTest.java
> +                "Your " + staticAttributeName + " static attribute is not initialized correctly.");
check the attribute exists before checking its value

2024-06-18 19:47 UTC, merged