oop-static_modifier-hard-q5
canvas-gamification/canvas-gamification-junit-tests pull request #721
Opened 2023-08-15 17:38 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:50 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-18 05:34 UTC, SamamthaH requested changes

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +      should not be visible from other classes.
```suggestion
    - A _static_ `double` called **materialAreaAvailable**. This represents the total number of carpet squares available for
      making `Carpet` objects, and should be set initially to 300 without having to call the constructor. Note that it
      should not be visible from other classes.
```

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +
Carpet squares are easy to order but the colour of different batches can be slightly different and so cannot be used for the same carpet. Write a Java class called `Carpet` to keep track of the carpet squares of the most recent order using the requirements below. Then write a class called `TestCoverage` to test `Carpet`.

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +      81, 100, 90.25, 156.25 then go through in order to floor them using `canCompleteFlooring` method. Finally, print
```suggestion
      81, 100, 90.25, 156.25. Then go through them in the same order to floor them using the `canCompleteFlooring` method. Finally, print
```

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +      the number of houses that can be floored in this format:
```suggestion
      how many of the houses can be floored in this format:
```

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +      "There is enough material for x houses" where x is the number of floorings made.
```suggestion
      "There is enough material for the first x houses" where x is the number of floorings made.
```

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/QuestionText.md
> +      "There is enough material for x houses" where x is the number of floorings made.
update the other strings as well

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +    @Order(3)
make this the first test

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +                Arguments.of(7.4, 0.5)
test a 0 case and a case with larger numbers

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +        String wrongValueMessage = "The %s constructor did not initialize the %s attribute to the correct value based on the parameters passed to the constructor.";
```suggestion
        String wrongValueMessage = "The %s constructor did not initialize the %s attribute to the correct value based on the parameter passed to the constructor.";
```

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +    public void canCompleteFlooringIsDefinedCorrectly() {
this test is no longer needed

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +        classObject.callMethod("main", new Object[][]{{new String[0], String[].class}}, new String[]{"public"}, classInstance,
add an error message

2024-03-18 05:34 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +                new StringLiteral("There is enough material for 2 houses"),
make this a variable at the top of the tests

2024-03-18 18:45 UTC, Hedgemon4 requested changes
See Sam's review

2024-04-07 21:56 UTC, SamamthaH requested changes

2024-04-07 21:56 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +        _assertEquals(initialBeams, testClass.getFieldValue(null, staticAttributeName),
check that the variable exists before checking its value

2024-04-07 21:56 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +        _assertEquals(value1, testClass.getFieldValue(checkupInstance, attributeName), String.format(wrongValueMessage, className, attributeName));
check that the constructor does not affect the static value

2024-04-07 21:56 UTC, SamamthaH commented on src/oop/static_modifier/hard/q5/MainTest.java
> +                "Your " + testClassName + " class main method does not print the correct output.");
would you be able to initialize a Carpet object before this method call and then compare it's values before and after the main method call to check if the student is actually modifying the static values?

2024-06-18 22:58 UTC, merged