oop-static_modifier-hard-q6
canvas-gamification/canvas-gamification-junit-tests pull request #722
Opened 2023-08-15 18:37 UTC by KaiKhademi

## PR Checklist
- [ ]  Are helper methods really needed here?
    > Opt for hardcoding input/output into the input provider when possible
- [ ]  Are the assertion fail messages good?
    - [ ]  Logical (does it make sense?)
    - [ ]  Readable (can a student understand what’s wrong?)
    - [ ]  Not too feed-y (does it give away the answer?)
    - [ ]  Grammatically sound (is the grammar and punctuation in the sentence proper?)
    - [ ]  Specific (does the fail message relate to the question?)
- [ ]  Is the code formatted well?
    > Run `CTRL` + `ALT` + `L` in IntelliJ
- [ ]  EOF newlines
- [ ]  Do the comments for Parsons follow the correct convention?
- [ ]  Is the question being tested sufficiently?
    - [ ]  Are there representative cases to test the program?
    - [ ]  What about edge cases? (empty strings, negatives, infinity, off-by-one errors, etc)
        > If the question doesn’t specify what to do, mark it as a bad question
- [ ]  Are the test method names good?
    > Test method names show up in a “What went well” section on the website, so “mathTest” will become “What went well: math test”, which doesn’t make much sense. A better name in this example would be “calculatesTaxCorrectly” so it shows up as “What went well: calculates tax correctly”

2023-09-08 16:50 UTC, Hedgemon4 requested changes
Please see my feedback on other questions in this category and apply it to this PR.

2024-03-18 05:54 UTC, SamamthaH requested changes

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      it should not be visible from other classes.
```suggestion
    - A _static_ `double` called **foodInSilo**. This represents the total number of food available in the silo for 
    `Farm` objects, and should be set initially to 50 without having to call the constructor. Note that
      it should not be visible from other classes.
```

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      it should not be visible from other classes.
change attribute name in the rest accordingly

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      but there is not enough for everyone here." otherwise.
```suggestion
    - A `feedAnimals` method which prints "Animals fed and happy." if the total food needed is less than the
      amount available in the **foodInSilo** variable, and subtract it from available food. If there is not enough
      food it should print "We need to buy more food." and subtract nothing.
```

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +Your `TestDontion` class must have the following items:
```suggestion
## TestFeeding Class

Your `TestFeeding` class must have the following items:
```

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      but there is not enough for everyone here." otherwise.
update other areas a relevant

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      it should try to donate food by printing "Try to donate here... " and using **recieveDonation** method until there
```suggestion
      it should try to donate food by printing "Try to feed animals here... " and using **recieveDonation** method until there
```

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +    @Order(3)
make this the first test

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +    public void receiveDonationIsDefinedCorrectly() {
this test is no longer needed

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +                    new StringLiteral("Thank you for your donation."),
make these strings variables at the top of the tests

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +    public void foodNeededIsDefinedCorrectly() {
move the contents of this test into  farmClassHasCorrectFoodNeededMethod

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +        testClass.callMethod(methodName2, classInstance, testSentence);
add an error message

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +        if (temp >= 0.5 * 10) {
store the numeric values as variables at the top of the tests

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +
Animals are an important part of farm life and require a lot of food. Write a Java class called `Farm` to keep track of the animals and available food using the requirements below. Then write a class called `TestFeeding` to test the `Farm` using the next set of requirements below.

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      can not be any food donated. Then it should print "There is no more food left today.". All prints are in separate lines.
It does not currently print "There is no more food left today."

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      can not be any food donated. Then it should print "There is no more food left today.". All prints are in separate lines.
```suggestion
      can not be any food donated. Then it should print "There is no more food left today." All prints are in separate lines.
```

2024-03-18 05:54 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +                    new StringLiteral("Thank you for your donation."),
The period in it should also be escaped since periods have a special meaning in regex

2024-03-18 18:45 UTC, Hedgemon4 requested changes
See Sam's review

2024-04-07 21:13 UTC, SamamthaH requested changes

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      can not be any food donated. Then it should print "There is no more food left today." All prints are in separate lines.
change TestFeeding to match this description. You are still not printing "There is no more food left today." or "Try to feed animals here..."

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +    public void farmClassHasCorrectReceiveDonationMethod(double value1, int value2, double value3) throws Throwable {
fix this name

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +
Add this as question text

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +    - A _static_ `double` called **foodInSilo**. This represents the total number of food available in the silo for
```suggestion
    - A _static_ `double` called **foodInSilo**. This represents the total amount of food available in the silo for
```

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/MainTest.java
> +    }
add a test that checks they don't alter the static value on calling the constructor

2024-04-07 21:13 UTC, SamamthaH commented on src/oop/static_modifier/hard/q6/QuestionText.md
> +      amount available in the **foodInSilo** variable, and subtract it from available food. If there is not enough
```suggestion
      amount available in the **foodInSilo** variable, and subtracts the value from the available food. If there is not enough
```

2024-06-19 01:30 UTC, merged