pre_defined_classes-mathematical_program-medium-q7
canvas-gamification/canvas-gamification-junit-tests pull request #86
Opened 2022-03-11 04:36 UTC by Hedgemon4

2022-03-11 17:47 UTC, SamamthaH approved these changes

2022-03-13 23:46 UTC, Opeyem1a requested changes

2022-03-13 23:46 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/medium/q7/MainTest.java
> +                new DoubleLiteral(220, 222, "waterSpeed"),
I think if you want to use DoubleLiteral to grab a specific value, then we shouldn't provide a range like this, I think it's best here to just not provide a range and let it catch any double.

My reasoning is that the default error message for when a number is outside the range will be something like "value for X is outside of range", but the student will have no idea what range we're talking about and the question has no ranged component. Best to reserve the range to cases where the range is critical

2022-03-18 20:31 UTC, Opeyem1a requested changes

2022-03-18 20:31 UTC, Opeyem1a commented on src/pre_defined_classes/mathematical_program/medium/q7/MainTest.java
> +        assertEquals(221.4 , Double.parseDouble(getItemByName("waterSpeed")), 0.2,  "Your calculated water speed is incorrect");
Format file and period at the end of the sentence

2022-03-25 02:56 UTC, aadiraju approved these changes
This is good now!

2022-03-25 20:11 UTC, Opeyem1a approved these changes

2022-04-01 22:48 UTC, Opeyem1a approved these changes

2022-04-01 22:48 UTC, merged